/**
 * scripts/seed-data.ts
 * Topics and questions for initial seed.
 * Questions extracted from QAForge.html prototype + expanded to 15+ per topic.
 */

export const TOPICS_DATA = [
  {
    name: 'Selenium WebDriver',
    slug: 'selenium-webdriver',
    description: 'Web browser automation with Selenium 4 and WebDriver protocol.',
    color: '#3B82F6',
    icon: 'Globe',
  },
  {
    name: 'Playwright',
    slug: 'playwright',
    description: 'Modern end-to-end testing with Playwright for Node.js.',
    color: '#2DD4BF',
    icon: 'Play',
  },
  {
    name: 'API Testing',
    slug: 'api-testing',
    description: 'REST and GraphQL API testing with tools like Postman and RestAssured.',
    color: '#10B981',
    icon: 'Wifi',
  },
  {
    name: 'Test Strategy',
    slug: 'test-strategy',
    description: 'Testing methodologies, test pyramid, risk-based testing, and quality principles.',
    color: '#A855F7',
    icon: 'Target',
  },
  {
    name: 'TestNG / JUnit',
    slug: 'testng-junit',
    description: 'Java testing frameworks: JUnit 5 annotations, TestNG features, and parameterization.',
    color: '#F59E0B',
    icon: 'FlaskConical',
  },
  {
    name: 'CI/CD',
    slug: 'cicd',
    description: 'Continuous Integration and Deployment pipelines, GitHub Actions, Jenkins.',
    color: '#EC4899',
    icon: 'GitBranch',
  },
  {
    name: 'SQL for QA',
    slug: 'sql-for-qa',
    description: 'Database testing, SQL queries for test data setup and validation.',
    color: '#F97316',
    icon: 'Database',
  },
  {
    name: 'Postman',
    slug: 'postman',
    description: 'API testing with Postman: collections, environments, scripts, and Newman.',
    color: '#EF4444',
    icon: 'Send',
  },
  {
    name: 'Java Basics for QA',
    slug: 'java-basics',
    description: 'Java fundamentals relevant to QA automation: OOP, collections, exceptions.',
    color: '#84CC16',
    icon: 'Code2',
  },
  {
    name: 'Agile / Scrum for QA',
    slug: 'agile-scrum',
    description: 'Agile testing practices, Scrum ceremonies, definition of done, and QA role in sprints.',
    color: '#06B6D4',
    icon: 'IterationCcw',
  },
]

// Questions keyed by topicSlug
type QuestionSeed = {
  topicSlug: string
  text: string
  type: 'multiple' | 'true_false' | 'open'
  difficulty: 'easy' | 'medium' | 'hard'
  options?: { label: 'A' | 'B' | 'C' | 'D'; text: string }[]
  correctAnswer: string | null
  explanation: string
  tags: string[]
  version: string | null
}

export const QUESTIONS_DATA: QuestionSeed[] = [

  // ── SELENIUM WEBDRIVER ──────────────────────────────────────────────────
  {
    topicSlug: 'selenium-webdriver',
    text: 'What happens when findElement() cannot locate the target element in the DOM?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'Returns null' },
      { label: 'B', text: 'Returns an empty WebElement list' },
      { label: 'C', text: 'Throws NoSuchElementException' },
      { label: 'D', text: 'Waits indefinitely' },
    ],
    correctAnswer: 'C',
    explanation: 'findElement() throws NoSuchElementException immediately. Use findElements() to get an empty list instead — safer when the element may or may not be present.',
    tags: ['locators', 'exceptions'],
    version: null,
  },
  {
    topicSlug: 'selenium-webdriver',
    text: 'Selenium WebDriver can directly automate native desktop applications (e.g. Windows Calculator).',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'false',
    explanation: 'Selenium exclusively automates web browsers. For native desktop apps use WinAppDriver, SikuliX, or Appium with its desktop driver.',
    tags: ['scope'],
    version: null,
  },
  {
    topicSlug: 'selenium-webdriver',
    text: 'Which wait strategy is best practice for handling dynamically loaded elements?',
    type: 'multiple',
    difficulty: 'medium',
    options: [
      { label: 'A', text: 'Thread.sleep(3000)' },
      { label: 'B', text: 'ImplicitWait with a large timeout' },
      { label: 'C', text: 'ExplicitWait with ExpectedConditions' },
      { label: 'D', text: 'PageLoadTimeout only' },
    ],
    correctAnswer: 'C',
    explanation: 'ExplicitWait + ExpectedConditions waits for a specific condition (e.g. elementToBeClickable). Precise and avoids unnecessary delays.',
    tags: ['waits', 'best-practices'],
    version: null,
  },
  {
    topicSlug: 'selenium-webdriver',
    text: 'Explain the Page Object Model (POM) pattern. What problem does it solve and what are two key benefits?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'POM creates one class per page/component encapsulating locators and interaction methods.\n\nProblem: Without POM, a locator change forces updates in every test that uses it.\n\nBenefits:\n1. Maintainability — UI changes updated in one place\n2. Readability — tests describe behavior, not selectors\n3. Reusability — page classes shared across test suites',
    tags: ['POM', 'design-patterns'],
    version: null,
  },
  {
    topicSlug: 'selenium-webdriver',
    text: 'In Selenium 4, how do you switch focus to a newly opened browser tab?',
    type: 'multiple',
    difficulty: 'hard',
    options: [
      { label: 'A', text: 'driver.switchTo().window(handle)' },
      { label: 'B', text: 'driver.getWindowHandles().switchToLast()' },
      { label: 'C', text: 'driver.focusTab(tabIndex)' },
      { label: 'D', text: 'driver.navigate().switchTab()' },
    ],
    correctAnswer: 'A',
    explanation: 'Use driver.switchTo().window(handle). Collect handles with driver.getWindowHandles(), then switch to the new one. Selenium 4 also added driver.switchTo().newWindow(WindowType.TAB).',
    tags: ['tabs', 'windows'],
    version: 'Selenium 4',
  },
  {
    topicSlug: 'selenium-webdriver',
    text: 'Which locator strategy is generally the most resilient to UI changes?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'XPath with absolute path' },
      { label: 'B', text: 'CSS selector by element ID' },
      { label: 'C', text: 'XPath by index' },
      { label: 'D', text: 'CSS selector by class name only' },
    ],
    correctAnswer: 'B',
    explanation: 'IDs are unique by HTML spec and rarely change during refactors. CSS by ID (#element-id) is fast and stable. Avoid absolute XPaths and index-based selectors — they break with layout changes.',
    tags: ['locators', 'css', 'xpath'],
    version: null,
  },
  {
    topicSlug: 'selenium-webdriver',
    text: 'WebDriverWait is a subclass of FluentWait in Selenium.',
    type: 'true_false',
    difficulty: 'medium',
    options: [],
    correctAnswer: 'true',
    explanation: 'WebDriverWait extends FluentWait<WebDriver>. FluentWait is the more flexible parent that lets you configure polling interval and ignored exceptions. WebDriverWait uses a default 500ms poll.',
    tags: ['waits', 'FluentWait'],
    version: null,
  },
  {
    topicSlug: 'selenium-webdriver',
    text: 'What is the difference between driver.close() and driver.quit() in Selenium?',
    type: 'open',
    difficulty: 'easy',
    options: [],
    correctAnswer: null,
    explanation: 'driver.close() closes only the currently focused browser window/tab, leaving other windows open.\n\ndriver.quit() closes all windows managed by the driver and ends the WebDriver session, releasing resources.\n\nBest practice: always call driver.quit() in teardown to avoid browser process leaks.',
    tags: ['driver', 'teardown'],
    version: null,
  },
  {
    topicSlug: 'selenium-webdriver',
    text: 'Which JavaScript executor method is used to scroll an element into view?',
    type: 'multiple',
    difficulty: 'medium',
    options: [
      { label: 'A', text: 'driver.scroll(element)' },
      { label: 'B', text: '((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", element)' },
      { label: 'C', text: 'Actions.scrollTo(element).perform()' },
      { label: 'D', text: 'driver.navigate().scrollTo(element)' },
    ],
    correctAnswer: 'B',
    explanation: 'JavascriptExecutor.executeScript() with scrollIntoView(true) scrolls the element to the top of the viewport. In Selenium 4 you can also use the Actions class with scrollToElement().',
    tags: ['javascript-executor', 'scroll'],
    version: null,
  },
  {
    topicSlug: 'selenium-webdriver',
    text: 'What is a StaleElementReferenceException and how do you handle it?',
    type: 'open',
    difficulty: 'hard',
    options: [],
    correctAnswer: null,
    explanation: 'Thrown when a reference to a WebElement is no longer valid — the DOM was updated (page reload, AJAX refresh, React re-render) after the element was located.\n\nHandling strategies:\n1. Re-locate the element before each interaction\n2. Wrap interactions in a retry loop that catches StaleElementReferenceException\n3. Use a helper method that re-finds the element on retry\n4. In POM, avoid caching WebElement fields; re-call findElement() each time',
    tags: ['exceptions', 'StaleElement', 'AJAX'],
    version: null,
  },
  {
    topicSlug: 'selenium-webdriver',
    text: 'In Selenium 4, Relative Locators allow finding elements relative to another element.',
    type: 'true_false',
    difficulty: 'medium',
    options: [],
    correctAnswer: 'true',
    explanation: 'Selenium 4 introduced Relative Locators (above, below, toLeftOf, toRightOf, near) to find elements based on their position relative to a known element in the viewport.',
    tags: ['locators', 'relative-locators'],
    version: 'Selenium 4',
  },
  {
    topicSlug: 'selenium-webdriver',
    text: 'How do you handle a file upload dialog in Selenium (without third-party tools)?',
    type: 'open',
    difficulty: 'hard',
    options: [],
    correctAnswer: null,
    explanation: 'For <input type="file"> elements: call sendKeys() with the absolute file path directly on the input element — no need to open the OS dialog.\n\nExample:\nWebElement upload = driver.findElement(By.id("file-input"));\nupload.sendKeys("/absolute/path/to/file.pdf");\n\nThis bypasses the OS file dialog entirely. For non-standard upload components, you may need Robot class or AutoIt.',
    tags: ['file-upload', 'sendKeys'],
    version: null,
  },
  {
    topicSlug: 'selenium-webdriver',
    text: 'Which component of Selenium Grid receives test requests and distributes them to nodes?',
    type: 'multiple',
    difficulty: 'hard',
    options: [
      { label: 'A', text: 'Hub' },
      { label: 'B', text: 'Node' },
      { label: 'C', text: 'Router' },
      { label: 'D', text: 'Distributor' },
    ],
    correctAnswer: 'A',
    explanation: 'In Selenium Grid 3, the Hub receives requests and routes to Nodes. In Selenium Grid 4 this was refactored into Router, Distributor, Session Map, and Node — but the conceptual Hub role maps to the Router+Distributor pair.',
    tags: ['grid', 'parallel', 'hub'],
    version: 'Selenium 4',
  },
  {
    topicSlug: 'selenium-webdriver',
    text: 'Actions class in Selenium is used for complex user gestures like hover, drag-and-drop, and keyboard chaining.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'The Actions class (from org.openqa.selenium.interactions) builds a chain of actions that are executed together via perform(). Supports mouse hover, click-and-hold, drag-and-drop, key down/up, and more.',
    tags: ['Actions', 'user-gestures'],
    version: null,
  },
  {
    topicSlug: 'selenium-webdriver',
    text: 'What is the purpose of the @FindBy annotation in Selenium PageFactory?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: '@FindBy is part of Selenium\'s PageFactory pattern. It annotates WebElement fields in a Page Object class with a locator strategy.\n\nPageFactory.initElements(driver, this) then lazily initializes them — the element is located when first accessed, not when the page object is constructed.\n\nExample:\n@FindBy(id = "username")\nprivate WebElement usernameField;\n\nNote: avoid caching the result of click/find — StaleElement risk. Re-init or call initElements again after navigation.',
    tags: ['POM', 'PageFactory', 'annotations'],
    version: null,
  },

  // ── PLAYWRIGHT ──────────────────────────────────────────────────────────
  {
    topicSlug: 'playwright',
    text: 'In Playwright, what is the recommended way to interact with an element — avoiding explicit waits?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'await page.waitForTimeout(3000)' },
      { label: 'B', text: "await page.waitForSelector('#btn')" },
      { label: 'C', text: "await page.locator('#btn').click() — auto-waits" },
      { label: 'D', text: "await element.waitFor({ state: 'visible' })" },
    ],
    correctAnswer: 'C',
    explanation: "Playwright locator actions (click, fill, etc.) auto-wait for the element to be visible, enabled, and stable. No explicit wait needed.",
    tags: ['locators', 'auto-wait'],
    version: null,
  },
  {
    topicSlug: 'playwright',
    text: 'Playwright can run tests in parallel across Chromium, Firefox, and WebKit in a single test run.',
    type: 'true_false',
    difficulty: 'medium',
    options: [],
    correctAnswer: 'true',
    explanation: 'Configure the "projects" array in playwright.config.ts to target multiple browsers simultaneously. Playwright will run all projects in parallel by default.',
    tags: ['cross-browser', 'parallel'],
    version: null,
  },
  {
    topicSlug: 'playwright',
    text: 'What is the primary purpose of page.route() in Playwright?',
    type: 'multiple',
    difficulty: 'medium',
    options: [
      { label: 'A', text: 'Navigate to a specific URL' },
      { label: 'B', text: 'Intercept and mock/abort HTTP requests' },
      { label: 'C', text: 'Configure route-based page objects' },
      { label: 'D', text: 'Set the base URL for all navigations' },
    ],
    correctAnswer: 'B',
    explanation: 'page.route() intercepts network requests matching a URL pattern — mock API responses, simulate 503 errors, or spy on request payloads without a real backend.',
    tags: ['network', 'mocking', 'route'],
    version: null,
  },
  {
    topicSlug: 'playwright',
    text: 'What is a Playwright fixture and what problem does it solve?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'A fixture is a reusable piece of test setup/teardown that is injected into tests via function arguments.\n\nProblem it solves: eliminates boilerplate beforeEach/afterEach blocks and makes dependencies explicit and composable.\n\nExample: the built-in `page` fixture automatically creates a new page, passes it to the test, and closes it afterward. Custom fixtures can encapsulate login state, DB connections, etc.',
    tags: ['fixtures', 'architecture'],
    version: null,
  },
  {
    topicSlug: 'playwright',
    text: 'In Playwright, which method do you use to take a screenshot of the full page?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'page.capture()' },
      { label: 'B', text: 'page.screenshot({ fullPage: true })' },
      { label: 'C', text: 'page.snapshot()' },
      { label: 'D', text: 'browser.screenshot()' },
    ],
    correctAnswer: 'B',
    explanation: 'page.screenshot({ fullPage: true }) captures the entire scrollable page, not just the visible viewport. You can also pass a path option to save it directly.',
    tags: ['screenshots', 'visual'],
    version: null,
  },
  {
    topicSlug: 'playwright',
    text: 'Playwright\'s toHaveScreenshot() assertion performs visual regression testing.',
    type: 'true_false',
    difficulty: 'medium',
    options: [],
    correctAnswer: 'true',
    explanation: 'toHaveScreenshot() compares the current screenshot against a stored baseline. On first run it creates the baseline; subsequent runs diff against it. Use --update-snapshots to refresh baselines.',
    tags: ['visual-regression', 'assertions'],
    version: null,
  },
  {
    topicSlug: 'playwright',
    text: 'What is the difference between page.locator() and page.getByRole() in Playwright?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'page.locator(selector) finds elements using CSS or XPath selectors — similar to Selenium.\n\npage.getByRole(role, options) queries by ARIA role (like a screen reader), making tests more resilient to HTML changes and naturally testing accessibility.\n\nBest practice: prefer getByRole(), getByText(), getByLabel() (semantic selectors) over CSS selectors. They reflect how users perceive the UI, not the implementation.',
    tags: ['locators', 'ARIA', 'accessibility'],
    version: null,
  },
  {
    topicSlug: 'playwright',
    text: 'What is Playwright\'s "browser context" and how does it differ from a browser instance?',
    type: 'open',
    difficulty: 'hard',
    options: [],
    correctAnswer: null,
    explanation: 'A Browser is the actual browser process (e.g., Chromium).\n\nA BrowserContext is an isolated "profile" within that browser — separate cookies, localStorage, session, cache. Like an incognito window.\n\nMultiple contexts can run within one browser process in parallel, each fully isolated. This makes parallel testing fast (one browser, many contexts) and enables multi-user scenarios (two contexts = two logged-in users).',
    tags: ['browser-context', 'isolation', 'parallel'],
    version: null,
  },
  {
    topicSlug: 'playwright',
    text: 'Which Playwright configuration property sets the base URL for all page.goto() calls?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'rootUrl' },
      { label: 'B', text: 'baseURL' },
      { label: 'C', text: 'origin' },
      { label: 'D', text: 'defaultUrl' },
    ],
    correctAnswer: 'B',
    explanation: 'Setting baseURL in playwright.config.ts (use: { baseURL }) allows you to call page.goto("/login") instead of the full URL. It also resolves relative URLs in page.route() patterns.',
    tags: ['config', 'baseURL'],
    version: null,
  },
  {
    topicSlug: 'playwright',
    text: 'Playwright supports testing mobile device viewports using device emulation.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: "Playwright ships with a devices map (e.g., devices['iPhone 14']). Use it in playwright.config.ts projects or pass it to browser.newContext(). It sets viewport, userAgent, touch, and deviceScaleFactor.",
    tags: ['mobile', 'emulation'],
    version: null,
  },
  {
    topicSlug: 'playwright',
    text: 'How do you store and reuse an authenticated state in Playwright to avoid logging in before every test?',
    type: 'open',
    difficulty: 'hard',
    options: [],
    correctAnswer: null,
    explanation: 'Use Playwright\'s storageState feature:\n\n1. Create a setup project that logs in and saves the auth state:\n   await page.context().storageState({ path: "auth.json" })\n\n2. In playwright.config.ts, set the dependency and storage state:\n   use: { storageState: "auth.json" }\n\nThis saves cookies and localStorage. Tests then start already logged in, skipping the login flow entirely. Much faster than re-authenticating per test.',
    tags: ['auth', 'storageState', 'performance'],
    version: null,
  },
  {
    topicSlug: 'playwright',
    text: 'In Playwright, expect(locator).toBeVisible() waits for the element automatically.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'All Playwright web-first assertions (toBeVisible, toHaveText, toBeEnabled, etc.) have built-in auto-waiting with configurable timeout. They retry until the condition is met or timeout is reached.',
    tags: ['assertions', 'auto-wait'],
    version: null,
  },
  {
    topicSlug: 'playwright',
    text: 'What is the purpose of test.describe() in Playwright?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'Marks a test as skipped' },
      { label: 'B', text: 'Groups related tests under a named suite' },
      { label: 'C', text: 'Defines a fixture for a test' },
      { label: 'D', text: 'Sets the timeout for all tests in the file' },
    ],
    correctAnswer: 'B',
    explanation: 'test.describe("group name", () => { ... }) groups related tests. You can nest describes, add hooks (beforeAll, beforeEach) scoped to the group, and use describe.only/skip.',
    tags: ['test-structure', 'describe'],
    version: null,
  },
  {
    topicSlug: 'playwright',
    text: 'Explain how Playwright traces work and when you would use them.',
    type: 'open',
    difficulty: 'hard',
    options: [],
    correctAnswer: null,
    explanation: 'A trace is a zip archive containing screenshots, DOM snapshots, network logs, and console output for a test run.\n\nEnable in config: trace: "on-first-retry" (or "on", "retain-on-failure").\nView with: npx playwright show-trace trace.zip (opens a timeline UI).\n\nUse when: debugging CI failures that are hard to reproduce locally. The timeline lets you step through each action and see the exact DOM/network state at each moment.',
    tags: ['debugging', 'traces', 'CI'],
    version: null,
  },
  {
    topicSlug: 'playwright',
    text: 'Which command generates a test by recording your browser interactions in Playwright?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'npx playwright record' },
      { label: 'B', text: 'npx playwright codegen <url>' },
      { label: 'C', text: 'npx playwright generate' },
      { label: 'D', text: 'npx playwright trace' },
    ],
    correctAnswer: 'B',
    explanation: 'npx playwright codegen <url> opens the browser with a code generation panel. Your actions are recorded as Playwright test code in real time.',
    tags: ['codegen', 'tooling'],
    version: null,
  },

  // ── API TESTING ─────────────────────────────────────────────────────────
  {
    topicSlug: 'api-testing',
    text: 'Which HTTP status code indicates a POST request successfully created a new resource?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: '200 OK' },
      { label: 'B', text: '201 Created' },
      { label: 'C', text: '204 No Content' },
      { label: 'D', text: '202 Accepted' },
    ],
    correctAnswer: 'B',
    explanation: '201 Created signals a resource was successfully created. The response typically includes a Location header with the new resource URI.',
    tags: ['status-codes', 'HTTP'],
    version: null,
  },
  {
    topicSlug: 'api-testing',
    text: 'REST APIs are stateless — the server retains no session information between requests.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'Statelessness is a core REST constraint. Every request must carry all needed information. The server never stores client session state.',
    tags: ['REST', 'stateless'],
    version: null,
  },
  {
    topicSlug: 'api-testing',
    text: 'What HTTP method should you use to PARTIALLY update an existing resource?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'PUT — replaces the whole resource' },
      { label: 'B', text: 'POST — creates new resources' },
      { label: 'C', text: 'PATCH — partially updates a resource' },
      { label: 'D', text: 'UPDATE — updates the resource' },
    ],
    correctAnswer: 'C',
    explanation: 'PATCH sends only the fields to change. PUT replaces the entire resource. There is no UPDATE HTTP verb.',
    tags: ['HTTP-methods', 'PATCH', 'PUT'],
    version: null,
  },
  {
    topicSlug: 'api-testing',
    text: 'Explain the difference between authentication and authorization in API testing. Give one test case for each.',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'Authentication = "Who are you?" — verifying identity.\nTest: call a protected endpoint with no token → expect 401 Unauthorized.\n\nAuthorization = "What can you do?" — verifying permissions.\nTest: call DELETE /users/{id} with a read-only token → expect 403 Forbidden.\n\nRule: 401 = not authenticated; 403 = authenticated but not permitted.',
    tags: ['auth', 'security', '401', '403'],
    version: null,
  },
  {
    topicSlug: 'api-testing',
    text: 'In Postman, a Pre-request Script executes AFTER the HTTP response is received.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'false',
    explanation: 'Pre-request Scripts run BEFORE the request is sent — to generate tokens, set variables, compute timestamps. Tests tab scripts run after the response.',
    tags: ['postman', 'scripts'],
    version: null,
  },
  {
    topicSlug: 'api-testing',
    text: 'What does idempotent mean for HTTP methods and which methods are idempotent?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'An idempotent operation produces the same result regardless of how many times it is called.\n\nIdempotent HTTP methods: GET, PUT, DELETE, HEAD, OPTIONS.\n\nNot idempotent: POST (calling twice creates two resources), PATCH (may be, depends on implementation).\n\nImportance for testing: you can safely retry idempotent requests without side effects — important for network failure handling.',
    tags: ['idempotent', 'HTTP-methods'],
    version: null,
  },
  {
    topicSlug: 'api-testing',
    text: 'Which HTTP status code should an API return when the request body fails validation (e.g., missing required field)?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: '500 Internal Server Error' },
      { label: 'B', text: '404 Not Found' },
      { label: 'C', text: '400 Bad Request' },
      { label: 'D', text: '422 Unprocessable Entity' },
    ],
    correctAnswer: 'C',
    explanation: '400 Bad Request is the standard for malformed or invalid request syntax/body. 422 Unprocessable Entity (more specific: semantic validation error on a well-formed request) is also acceptable and increasingly preferred by modern APIs.',
    tags: ['status-codes', 'validation'],
    version: null,
  },
  {
    topicSlug: 'api-testing',
    text: 'What is contract testing and how does it differ from integration testing?',
    type: 'open',
    difficulty: 'hard',
    options: [],
    correctAnswer: null,
    explanation: 'Contract testing verifies that a consumer (e.g., frontend) and a provider (e.g., API) agree on the interface — request format, response schema, status codes.\n\nTools: Pact (consumer-driven contract testing).\n\nDifference from integration testing:\n- Integration tests run both services together (slower, needs full environment).\n- Contract tests run independently — provider validates the contract without the consumer running, and vice versa.\n\nBenefit: detect breaking API changes before deployment without full E2E environments.',
    tags: ['contract-testing', 'Pact', 'microservices'],
    version: null,
  },
  {
    topicSlug: 'api-testing',
    text: 'A 429 HTTP status code means the client has sent too many requests in a given time period.',
    type: 'true_false',
    difficulty: 'medium',
    options: [],
    correctAnswer: 'true',
    explanation: '429 Too Many Requests indicates rate limiting. The response may include a Retry-After header. QA should test rate limiting boundaries as a security and reliability concern.',
    tags: ['status-codes', 'rate-limiting'],
    version: null,
  },
  {
    topicSlug: 'api-testing',
    text: 'What are the main differences between SOAP and REST APIs?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'SOAP (Simple Object Access Protocol):\n- Protocol with strict standards (WSDL, XML envelope)\n- Transport: HTTP, SMTP, etc.\n- Built-in error handling (Fault)\n- Verbose, heavy XML\n\nREST (Representational State Transfer):\n- Architectural style, not a protocol\n- Uses standard HTTP methods + JSON/XML\n- Lightweight, human-readable\n- Stateless\n\nFor testing: SOAP tested via SoapUI; REST via Postman, RestAssured, Playwright APIRequestContext.',
    tags: ['SOAP', 'REST', 'comparison'],
    version: null,
  },
  {
    topicSlug: 'api-testing',
    text: 'Which assertion would you use in Postman to verify the response time is under 500ms?',
    type: 'multiple',
    difficulty: 'medium',
    options: [
      { label: 'A', text: 'pm.test("Fast", () => pm.response.responseTime < 500)' },
      { label: 'B', text: 'pm.test("Fast", () => pm.expect(pm.response.responseTime).to.be.below(500))' },
      { label: 'C', text: 'pm.response.assertTime(500)' },
      { label: 'D', text: 'pm.expect(response.time).lessThan(500)' },
    ],
    correctAnswer: 'B',
    explanation: 'In Postman Tests tab: pm.expect(pm.response.responseTime).to.be.below(500) uses Chai-style assertions. pm.response.responseTime is the actual time in milliseconds.',
    tags: ['postman', 'performance', 'assertions'],
    version: null,
  },
  {
    topicSlug: 'api-testing',
    text: 'What is JSON Schema validation and why is it useful in API testing?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'JSON Schema is a specification for validating the structure, types, and constraints of JSON documents.\n\nIn API testing:\n- Verify response shape matches what the contract promises\n- Catch breaking changes (missing fields, type changes) automatically\n- Usable in Postman (pm.response.to.have.jsonSchema(schema)), Jest (ajv), RestAssured\n\nExample: assert that every item in an array response has an "id" (string) and "name" (string), even as data values change between runs.',
    tags: ['json-schema', 'validation', 'contract'],
    version: null,
  },
  {
    topicSlug: 'api-testing',
    text: 'Which HTTP method is used to retrieve resource metadata without returning the response body?',
    type: 'multiple',
    difficulty: 'medium',
    options: [
      { label: 'A', text: 'GET' },
      { label: 'B', text: 'OPTIONS' },
      { label: 'C', text: 'HEAD' },
      { label: 'D', text: 'TRACE' },
    ],
    correctAnswer: 'C',
    explanation: 'HEAD is identical to GET but the server returns only the headers, not the body. Use it to check if a resource exists, get its Content-Type/Content-Length, or verify cache headers — without downloading the full content.',
    tags: ['HTTP-methods', 'HEAD'],
    version: null,
  },
  {
    topicSlug: 'api-testing',
    text: 'CORS headers are a client-side security measure controlled by the browser.',
    type: 'true_false',
    difficulty: 'medium',
    options: [],
    correctAnswer: 'true',
    explanation: 'CORS (Cross-Origin Resource Sharing) is enforced by the browser, not the server. The server just sends the appropriate headers (Access-Control-Allow-Origin, etc.). API tools like Postman, curl, and automated tests bypass CORS entirely since they are not browsers.',
    tags: ['CORS', 'security'],
    version: null,
  },
  {
    topicSlug: 'api-testing',
    text: 'What does it mean to test an API for idempotency and how would you do it?',
    type: 'open',
    difficulty: 'hard',
    options: [],
    correctAnswer: null,
    explanation: 'Testing idempotency means verifying that calling the same request multiple times produces the same result as calling it once.\n\nApproach for PUT:\n1. Send PUT /users/1 with a payload\n2. Verify the response (201 or 200)\n3. Send the exact same PUT /users/1 again\n4. Verify you get the same response AND the resource state is identical to after step 2\n\nFor DELETE:\n1. DELETE /resource/1 → 200/204\n2. DELETE /resource/1 again → 404 (resource gone) but no server error\n\nIdempotency bugs: a PUT that creates a new resource on each call, a DELETE that throws 500 on a second call.',
    tags: ['idempotent', 'PUT', 'DELETE', 'testing-technique'],
    version: null,
  },

  // ── TEST STRATEGY ───────────────────────────────────────────────────────
  {
    topicSlug: 'test-strategy',
    text: 'According to the Test Pyramid, which layer should contain the MOST tests?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'E2E / UI tests' },
      { label: 'B', text: 'Integration tests' },
      { label: 'C', text: 'Unit tests' },
      { label: 'D', text: 'Manual exploratory tests' },
    ],
    correctAnswer: 'C',
    explanation: 'Test Pyramid (Mike Cohn): many fast unit tests at the base, fewer integration tests in the middle, very few E2E tests at the top.',
    tags: ['test-pyramid', 'strategy'],
    version: null,
  },
  {
    topicSlug: 'test-strategy',
    text: '"Shift-left testing" means integrating testing activities earlier in the software development lifecycle.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'Shift-left moves testing earlier in the SDLC. QAs review requirements and write tests during development — bugs found early are exponentially cheaper to fix.',
    tags: ['shift-left', 'SDLC'],
    version: null,
  },
  {
    topicSlug: 'test-strategy',
    text: 'Which technique derives test cases from requirements WITHOUT knowledge of internal code?',
    type: 'multiple',
    difficulty: 'medium',
    options: [
      { label: 'A', text: 'White-box testing' },
      { label: 'B', text: 'Black-box testing' },
      { label: 'C', text: 'Grey-box testing' },
      { label: 'D', text: 'Mutation testing' },
    ],
    correctAnswer: 'B',
    explanation: 'Black-box testing treats the system as opaque — inputs and expected outputs only, no code knowledge.',
    tags: ['black-box', 'testing-techniques'],
    version: null,
  },
  {
    topicSlug: 'test-strategy',
    text: 'Explain the difference between Verification and Validation in software testing.',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'Verification: "Are we building the product right?" — checking against specifications. Static: reviews, inspections.\n\nValidation: "Are we building the right product?" — checking against user needs. Dynamic: running the software.\n\nMnemonic: Verification = spec compliance; Validation = user satisfaction.',
    tags: ['verification', 'validation', 'QA-principles'],
    version: null,
  },
  {
    topicSlug: 'test-strategy',
    text: 'What is exploratory testing and when is it most valuable?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'Exploratory testing is simultaneous learning, test design, and execution — unscripted, guided by the tester\'s intuition and risk assessment.\n\nMost valuable when:\n- Requirements are incomplete or ambiguous\n- New feature areas not covered by automated tests\n- After a major refactor to uncover unexpected side effects\n- Time-boxed "bug hunts" near release\n\nNot a replacement for structured testing, but a complement to find what scripted tests miss.',
    tags: ['exploratory-testing', 'manual-testing'],
    version: null,
  },
  {
    topicSlug: 'test-strategy',
    text: 'Risk-based testing prioritizes test cases based on the probability and impact of failure.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'Risk = likelihood × impact. High-risk areas (complex, frequently changed, business-critical) get more thorough testing. Lower-risk stable modules get less coverage. This optimizes limited testing time.',
    tags: ['risk-based-testing', 'prioritization'],
    version: null,
  },
  {
    topicSlug: 'test-strategy',
    text: 'What is Equivalence Partitioning and how does it reduce the number of test cases?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'Equivalence Partitioning divides input data into groups (partitions) where all values in the group are expected to be treated the same way by the system.\n\nTest one value per partition instead of all values.\n\nExample — age field (must be 18–65):\n- Invalid partition 1: < 18 (test: 10)\n- Valid partition: 18–65 (test: 30)\n- Invalid partition 2: > 65 (test: 70)\n\nResult: 3 test cases cover the entire input space.',
    tags: ['equivalence-partitioning', 'test-design'],
    version: null,
  },
  {
    topicSlug: 'test-strategy',
    text: 'In Boundary Value Analysis, test cases should focus on values AT and ADJACENT TO partition boundaries.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'BVA tests boundary values because most bugs occur there. For a valid range 18–65: test 17, 18, 19 (lower boundary) and 64, 65, 66 (upper boundary).',
    tags: ['BVA', 'boundary-testing', 'test-design'],
    version: null,
  },
  {
    topicSlug: 'test-strategy',
    text: 'Which testing type focuses specifically on how the system behaves under expected and peak load conditions?',
    type: 'multiple',
    difficulty: 'medium',
    options: [
      { label: 'A', text: 'Stress testing' },
      { label: 'B', text: 'Load testing' },
      { label: 'C', text: 'Spike testing' },
      { label: 'D', text: 'Soak testing' },
    ],
    correctAnswer: 'B',
    explanation: 'Load testing simulates expected concurrent user loads to verify the system meets performance requirements. Stress testing pushes BEYOND limits. Spike testing applies sudden large bursts. Soak testing checks for degradation over long periods.',
    tags: ['performance-testing', 'load-testing'],
    version: null,
  },
  {
    topicSlug: 'test-strategy',
    text: 'Describe the Testing Trophy (Kent C. Dodds) and how it differs from the Test Pyramid.',
    type: 'open',
    difficulty: 'hard',
    options: [],
    correctAnswer: null,
    explanation: 'Testing Trophy (Dodds) suggests investing most in integration tests:\n- Static analysis (TypeScript, ESLint) — catches errors without running\n- Unit tests — small, isolated\n- Integration tests — MOST value: test how units work together (API routes, components with dependencies)\n- E2E — few, covering critical user flows\n\nDifference from Pyramid: the Pyramid emphasizes unit tests as the base. The Trophy argues that integration tests provide the highest ROI — they test realistic behavior without the brittle nature of E2E.',
    tags: ['testing-trophy', 'test-pyramid', 'architecture'],
    version: null,
  },
  {
    topicSlug: 'test-strategy',
    text: 'Regression testing is performed to ensure that new code changes have not broken existing functionality.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'Regression testing re-runs existing test cases after any change (new feature, bug fix, refactor) to confirm the system still works as expected. Automation is essential for regression because it must run frequently.',
    tags: ['regression-testing', 'automation'],
    version: null,
  },
  {
    topicSlug: 'test-strategy',
    text: 'What is the difference between a test plan and a test strategy?',
    type: 'open',
    difficulty: 'hard',
    options: [],
    correctAnswer: null,
    explanation: 'Test Strategy: high-level document defining the overall testing approach for an organization or project. Covers: objectives, test levels, types, tools, environments, entry/exit criteria. Long-lived, often project-independent.\n\nTest Plan: project-specific document derived from the strategy. Covers: scope, resources, schedule, specific test cases, risks. Changes per project/sprint.\n\nAnalogy: strategy = "how we test in general"; plan = "how we test this specific release".',
    tags: ['test-plan', 'test-strategy', 'documentation'],
    version: null,
  },
  {
    topicSlug: 'test-strategy',
    text: 'Which principle states that a small number of modules contains most of the defects found during testing?',
    type: 'multiple',
    difficulty: 'medium',
    options: [
      { label: 'A', text: 'Pesticide paradox' },
      { label: 'B', text: 'Defect clustering' },
      { label: 'C', text: 'Absence-of-errors fallacy' },
      { label: 'D', text: 'Early testing principle' },
    ],
    correctAnswer: 'B',
    explanation: 'Defect clustering (one of the 7 ISTQB testing principles): a small number of modules or features tend to contain the majority of defects. Focus testing effort on high-risk, historically buggy areas.',
    tags: ['ISTQB', 'defect-clustering', 'testing-principles'],
    version: null,
  },
  {
    topicSlug: 'test-strategy',
    text: 'What is smoke testing and how does it differ from sanity testing?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'Smoke testing: a shallow, broad check that the most critical functions of the build work — "does it turn on?" Runs first after a new build. If smoke fails, no further testing; reject the build.\n\nSanity testing: narrow, deep check of a specific area after a bug fix or minor change — "does this specific thing still work?" Subset of regression.\n\nKey difference: smoke = overall build stability; sanity = specific feature stability after change.',
    tags: ['smoke-testing', 'sanity-testing'],
    version: null,
  },
  {
    topicSlug: 'test-strategy',
    text: 'Mutation testing measures the effectiveness of your test suite by introducing deliberate code changes.',
    type: 'true_false',
    difficulty: 'hard',
    options: [],
    correctAnswer: 'true',
    explanation: 'Mutation testing tools (Pitest for Java, Stryker for JS) introduce small code changes ("mutants") and run the test suite. If tests FAIL, the mutant is "killed" (good). If tests PASS despite the mutation, the mutant "survived" — indicating a gap in test coverage.',
    tags: ['mutation-testing', 'test-quality'],
    version: null,
  },

  // ── TESTNG / JUNIT ──────────────────────────────────────────────────────
  {
    topicSlug: 'testng-junit',
    text: 'In JUnit 5, which annotation runs a setup method before EACH individual test?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: '@Before (JUnit 4 only)' },
      { label: 'B', text: '@BeforeEach' },
      { label: 'C', text: '@BeforeAll' },
      { label: 'D', text: '@Setup' },
    ],
    correctAnswer: 'B',
    explanation: 'JUnit 5: @Before → @BeforeEach (before every test method), @BeforeClass → @BeforeAll (once before all tests, must be static by default).',
    tags: ['JUnit5', 'lifecycle', 'annotations'],
    version: 'JUnit 5',
  },
  {
    topicSlug: 'testng-junit',
    text: "TestNG's @DataProvider enables parameterized tests — running the same test method once per data row.",
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: '@DataProvider returns Object[][] — each inner array is one set of parameters. The test runs once per row.',
    tags: ['TestNG', 'DataProvider', 'parameterized'],
    version: null,
  },
  {
    topicSlug: 'testng-junit',
    text: 'When no priority is set, in what order does TestNG run @Test methods by default?',
    type: 'multiple',
    difficulty: 'medium',
    options: [
      { label: 'A', text: 'Alphabetical order by method name' },
      { label: 'B', text: 'Declaration order in source file' },
      { label: 'C', text: 'Random order per run' },
      { label: 'D', text: 'TestNG selects an optimal order' },
    ],
    correctAnswer: 'A',
    explanation: 'Default TestNG order is alphabetical by method name. Use @Test(priority=1) to control it.',
    tags: ['TestNG', 'test-order', 'priority'],
    version: null,
  },
  {
    topicSlug: 'testng-junit',
    text: 'Explain the difference between @BeforeAll and @BeforeEach in JUnit 5, and give a use case for each.',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: '@BeforeAll: runs ONCE before any test. Must be static. Use for expensive setup: starting a DB, launching a browser.\n\n@BeforeEach: runs before every test method. Use for resetting state: clearing mocks, creating fresh test data.',
    tags: ['JUnit5', 'lifecycle', 'BeforeAll', 'BeforeEach'],
    version: 'JUnit 5',
  },
  {
    topicSlug: 'testng-junit',
    text: 'In JUnit 5, which annotation marks a test that should not be run?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: '@Skip' },
      { label: 'B', text: '@Disabled' },
      { label: 'C', text: '@Ignore' },
      { label: 'D', text: '@Exclude' },
    ],
    correctAnswer: 'B',
    explanation: '@Disabled in JUnit 5 (equivalent to @Ignore in JUnit 4) prevents a test or class from running. Optionally accepts a reason string: @Disabled("Bug #1234 not fixed yet").',
    tags: ['JUnit5', 'Disabled', 'annotations'],
    version: 'JUnit 5',
  },
  {
    topicSlug: 'testng-junit',
    text: 'TestNG supports test dependency — a test can depend on another test passing before it runs.',
    type: 'true_false',
    difficulty: 'medium',
    options: [],
    correctAnswer: 'true',
    explanation: '@Test(dependsOnMethods = {"loginTest"}) makes a test run only if loginTest passes. If the dependency fails, the dependent test is skipped (SKIP, not FAIL). Useful for sequential workflow tests.',
    tags: ['TestNG', 'dependsOnMethods', 'dependencies'],
    version: null,
  },
  {
    topicSlug: 'testng-junit',
    text: 'What is the purpose of soft assertions in TestNG and how do they differ from hard assertions?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'Hard assertions (Assert.*): stop test execution immediately on failure. One failure = test ends.\n\nSoft assertions (SoftAssert): collect all assertion failures and report them at the end of the test. Execution continues after a failure.\n\nUsage:\nSoftAssert sa = new SoftAssert();\nsa.assertEquals(actual1, expected1);\nsa.assertEquals(actual2, expected2);\nsa.assertAll(); // throws if any assertions failed\n\nUse soft assertions when you want to check multiple conditions in a single test run without stopping at the first failure.',
    tags: ['TestNG', 'SoftAssert', 'assertions'],
    version: null,
  },
  {
    topicSlug: 'testng-junit',
    text: 'In JUnit 5, @ParameterizedTest with @ValueSource runs a test once per provided value.',
    type: 'true_false',
    difficulty: 'medium',
    options: [],
    correctAnswer: 'true',
    explanation: '@ParameterizedTest + @ValueSource(strings = {"a", "b", "c"}) runs the test 3 times, once per value. JUnit 5 also offers @CsvSource, @MethodSource, and @EnumSource.',
    tags: ['JUnit5', 'ParameterizedTest', 'parameterized'],
    version: 'JUnit 5',
  },
  {
    topicSlug: 'testng-junit',
    text: 'How does TestNG handle test grouping and how is it different from JUnit 5 tags?',
    type: 'open',
    difficulty: 'hard',
    options: [],
    correctAnswer: null,
    explanation: 'TestNG groups: @Test(groups = {"smoke", "regression"}). Groups are defined in testng.xml:\n<groups><run><include name="smoke"/></run></groups>\n\nJUnit 5 tags: @Tag("smoke"). Controlled via Maven/Gradle build config or IDE run configurations.\n\nKey difference: TestNG groups are more powerful — you can include/exclude groups per XML suite, set group dependencies (dependsOnGroups), and run specific groups per environment.\n\nJUnit 5 tags are simpler and more portable across build tools.',
    tags: ['TestNG', 'JUnit5', 'groups', 'tags'],
    version: null,
  },
  {
    topicSlug: 'testng-junit',
    text: 'Which JUnit 5 extension replaces the @Rule mechanism from JUnit 4?',
    type: 'multiple',
    difficulty: 'hard',
    options: [
      { label: 'A', text: '@ExtendWith' },
      { label: 'B', text: '@RunWith' },
      { label: 'C', text: '@ClassRule' },
      { label: 'D', text: '@Plugin' },
    ],
    correctAnswer: 'A',
    explanation: '@ExtendWith(MyExtension.class) in JUnit 5 replaces @RunWith (JUnit 4 runner) and @Rule/@ClassRule. Extensions implement specific interfaces (BeforeEachCallback, ParameterResolver, etc.) for clean extension points.',
    tags: ['JUnit5', 'extensions', 'migration'],
    version: 'JUnit 5',
  },
  {
    topicSlug: 'testng-junit',
    text: 'What is the purpose of ITestListener in TestNG?',
    type: 'open',
    difficulty: 'hard',
    options: [],
    correctAnswer: null,
    explanation: 'ITestListener is an interface that lets you hook into TestNG\'s test lifecycle events:\n- onTestStart(ITestResult)\n- onTestSuccess / onTestFailure / onTestSkipped\n- onStart(ITestContext) / onFinish\n\nCommon uses:\n1. Custom reporting / logging\n2. Capturing screenshots on failure\n3. Sending test results to external systems (Slack, JIRA)\n4. Starting/stopping server resources\n\nRegister via testng.xml <listeners> or @Listeners annotation on the class.',
    tags: ['TestNG', 'ITestListener', 'reporting'],
    version: null,
  },
  {
    topicSlug: 'testng-junit',
    text: 'In JUnit 5, @RepeatedTest(5) runs the annotated test method 5 times.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: '@RepeatedTest(n) runs a test n times. Useful for verifying consistency of flaky behavior. The RepetitionInfo parameter can be injected to get current repetition number.',
    tags: ['JUnit5', 'RepeatedTest'],
    version: 'JUnit 5',
  },
  {
    topicSlug: 'testng-junit',
    text: 'What is the difference between assertEquals and assertSame in JUnit/TestNG?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'assertEquals(expected, actual): checks VALUE equality — calls .equals() under the hood. Two different objects with the same content pass.\n\nassertSame(expected, actual): checks REFERENCE equality — uses ==. Both must point to the exact same object in memory.\n\nExample:\nString a = new String("hello");\nString b = new String("hello");\nassertEquals(a, b); // PASSES — same value\nassertSame(a, b);    // FAILS — different objects in memory',
    tags: ['assertions', 'assertEquals', 'assertSame'],
    version: null,
  },
  {
    topicSlug: 'testng-junit',
    text: 'TestNG allows running tests in parallel at which levels?',
    type: 'multiple',
    difficulty: 'hard',
    options: [
      { label: 'A', text: 'Methods only' },
      { label: 'B', text: 'Classes only' },
      { label: 'C', text: 'Methods, classes, suites, and tests' },
      { label: 'D', text: 'Suites only' },
    ],
    correctAnswer: 'C',
    explanation: 'TestNG parallel attribute in testng.xml can be set to: methods (each @Test in its own thread), classes (all methods in a class share a thread), tests (each <test> tag in parallel), or suites (each <suite> in parallel).',
    tags: ['TestNG', 'parallel', 'configuration'],
    version: null,
  },

  // ── CI/CD ───────────────────────────────────────────────────────────────
  {
    topicSlug: 'cicd',
    text: 'What is the primary goal of Continuous Integration (CI) from a QA perspective?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'Automatically deploy to production' },
      { label: 'B', text: 'Build and run tests on every commit' },
      { label: 'C', text: 'Schedule manual regression cycles' },
      { label: 'D', text: 'Monitor app performance in production' },
    ],
    correctAnswer: 'B',
    explanation: 'CI automatically builds and tests on every commit. Goal: detect integration defects immediately. A red pipeline = stop and fix before moving on.',
    tags: ['CI', 'automation'],
    version: null,
  },
  {
    topicSlug: 'cicd',
    text: '"Fail fast" in CI/CD means halting the pipeline immediately when a critical test fails.',
    type: 'true_false',
    difficulty: 'medium',
    options: [],
    correctAnswer: 'true',
    explanation: "If smoke tests fail, there's no point running the full regression suite. Stop and notify the team immediately.",
    tags: ['fail-fast', 'pipeline'],
    version: null,
  },
  {
    topicSlug: 'cicd',
    text: 'Explain the difference between Continuous Delivery and Continuous Deployment.',
    type: 'open',
    difficulty: 'hard',
    options: [],
    correctAnswer: null,
    explanation: 'Continuous Delivery: every passing build is production-ready but a human triggers the release.\n\nContinuous Deployment: every passing build is automatically deployed — NO human gate.\n\nKey: Delivery = manual trigger; Deployment = fully automated. Both require a solid automated test suite.',
    tags: ['CD', 'delivery', 'deployment'],
    version: null,
  },
  {
    topicSlug: 'cicd',
    text: 'Which GitHub Actions file format is used to define a workflow?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'JSON (.json)' },
      { label: 'B', text: 'XML (.xml)' },
      { label: 'C', text: 'YAML (.yml / .yaml)' },
      { label: 'D', text: 'TOML (.toml)' },
    ],
    correctAnswer: 'C',
    explanation: 'GitHub Actions workflows are defined in YAML files stored in .github/workflows/. They define triggers (on:), jobs, steps, and actions.',
    tags: ['GitHub-Actions', 'YAML'],
    version: null,
  },
  {
    topicSlug: 'cicd',
    text: 'A build artifact in CI/CD is a file or set of files produced by the build process.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'Artifacts are the outputs of a build: compiled binaries, Docker images, test reports, coverage reports. CI/CD pipelines typically archive artifacts so they can be deployed or inspected.',
    tags: ['artifacts', 'build'],
    version: null,
  },
  {
    topicSlug: 'cicd',
    text: 'What are the typical stages in a CI/CD pipeline from commit to production?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'Typical stages:\n1. Trigger: push/PR event\n2. Build: compile code, install dependencies\n3. Static analysis: linting, type-check, security scan\n4. Unit tests: fast, isolated\n5. Integration tests: API, DB, services\n6. Build artifact: Docker image, JAR, etc.\n7. Deploy to staging\n8. E2E / smoke tests against staging\n9. Approval gate (Continuous Delivery) or auto-deploy (Continuous Deployment)\n10. Deploy to production\n11. Post-deploy smoke test\n\nEach stage should fail fast and notify the team.',
    tags: ['pipeline', 'stages', 'CICD'],
    version: null,
  },
  {
    topicSlug: 'cicd',
    text: 'In Jenkins, a Declarative Pipeline is defined inside a "pipeline {}" block.',
    type: 'true_false',
    difficulty: 'medium',
    options: [],
    correctAnswer: 'true',
    explanation: 'Jenkins Declarative Pipeline uses a structured pipeline {} block with stages → stage → steps. Scripted Pipeline uses node {} with a Groovy DSL. Declarative is simpler and recommended for most use cases.',
    tags: ['Jenkins', 'pipeline', 'declarative'],
    version: null,
  },
  {
    topicSlug: 'cicd',
    text: 'What is a pipeline gate or quality gate in CI/CD?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'A quality gate is a set of criteria the build/tests must meet before proceeding to the next pipeline stage.\n\nExamples:\n- Code coverage > 80%\n- 0 critical security vulnerabilities (SonarQube)\n- All smoke tests pass before E2E suite\n- Performance tests within SLA thresholds\n\nIf a gate fails, the pipeline stops and does not deploy. This prevents low-quality code from reaching production. Common tools: SonarQube, GitHub branch protection rules, deployment approvals.',
    tags: ['quality-gate', 'pipeline', 'SonarQube'],
    version: null,
  },
  {
    topicSlug: 'cicd',
    text: 'Which deployment strategy gradually shifts traffic from the old version to the new version?',
    type: 'multiple',
    difficulty: 'hard',
    options: [
      { label: 'A', text: 'Blue-green deployment' },
      { label: 'B', text: 'Canary deployment' },
      { label: 'C', text: 'Rolling deployment' },
      { label: 'D', text: 'Recreate deployment' },
    ],
    correctAnswer: 'B',
    explanation: 'Canary deployment routes a small percentage of traffic (e.g., 5%) to the new version. If metrics are healthy, traffic gradually increases. Blue-green switches all traffic at once between two identical environments. Rolling updates instances incrementally.',
    tags: ['deployment-strategies', 'canary', 'blue-green'],
    version: null,
  },
  {
    topicSlug: 'cicd',
    text: 'What is test parallelization in CI and why is it important?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'Test parallelization runs multiple tests or test suites simultaneously across multiple agents/processes, reducing total CI run time.\n\nWhy important:\n- Fast feedback: developers can\'t wait 30+ minutes for a test suite\n- Cost: fewer total minutes of CI worker time if parallelized correctly\n- Merge queues: parallel tests unblock multiple PRs\n\nApproaches:\n- Split tests by file/folder across workers\n- Playwright: workers config in playwright.config.ts\n- TestNG: parallel="methods" in testng.xml\n- GitHub Actions: matrix strategy for parallel jobs',
    tags: ['parallelization', 'CI', 'performance'],
    version: null,
  },
  {
    topicSlug: 'cicd',
    text: 'Docker containers in CI ensure consistent test environments across different machines.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'Docker containers package the application and all its dependencies. "Works on my machine" issues disappear because the container runs identically everywhere — developer laptop, CI runner, staging, and production.',
    tags: ['Docker', 'containerization', 'CI'],
    version: null,
  },
  {
    topicSlug: 'cicd',
    text: 'What is a feature flag and how does it relate to CI/CD?',
    type: 'open',
    difficulty: 'hard',
    options: [],
    correctAnswer: null,
    explanation: 'A feature flag (toggle) is a configuration switch that enables/disables code paths without deploying new code.\n\nRelation to CI/CD:\n- Enables trunk-based development: incomplete features are merged but flagged off\n- Deploy frequently without exposing unfinished work\n- Gradual rollout: enable for 10% of users, monitor, then 100%\n- Instant rollback: turn off the flag without a deploy\n\nFrom a QA perspective: test both states (flag on AND off). Include flag state in test reports.',
    tags: ['feature-flags', 'trunk-based', 'rollout'],
    version: null,
  },
  {
    topicSlug: 'cicd',
    text: 'In a GitHub Actions workflow, the "on: pull_request" trigger runs the workflow when a PR is opened or updated.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'on: pull_request triggers on PR opened, synchronize (new commits pushed), and reopened by default. You can specify branches: [main] to only trigger on PRs targeting main.',
    tags: ['GitHub-Actions', 'triggers', 'pull-request'],
    version: null,
  },

  // ── SQL FOR QA ───────────────────────────────────────────────────────────
  {
    topicSlug: 'sql-for-qa',
    text: 'Which SQL clause filters rows AFTER GROUP BY aggregation?',
    type: 'multiple',
    difficulty: 'medium',
    options: [
      { label: 'A', text: 'WHERE' },
      { label: 'B', text: 'HAVING' },
      { label: 'C', text: 'FILTER' },
      { label: 'D', text: 'ORDER BY' },
    ],
    correctAnswer: 'B',
    explanation: 'WHERE filters rows before aggregation. HAVING filters grouped results after GROUP BY. Example: SELECT city, COUNT(*) FROM users GROUP BY city HAVING COUNT(*) > 10.',
    tags: ['SQL', 'GROUP-BY', 'HAVING'],
    version: null,
  },
  {
    topicSlug: 'sql-for-qa',
    text: 'NULL = NULL evaluates to TRUE in SQL.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'false',
    explanation: 'NULL represents the absence of a value. NULL = NULL is NULL (unknown), not TRUE. Use IS NULL or IS NOT NULL to check for null values.',
    tags: ['SQL', 'NULL'],
    version: null,
  },
  {
    topicSlug: 'sql-for-qa',
    text: 'What is the difference between INNER JOIN and LEFT JOIN?',
    type: 'open',
    difficulty: 'easy',
    options: [],
    correctAnswer: null,
    explanation: 'INNER JOIN: returns only rows that have matching values in BOTH tables. Rows with no match are excluded.\n\nLEFT JOIN (LEFT OUTER JOIN): returns ALL rows from the LEFT table and matching rows from the right table. If no match, right side columns are NULL.\n\nQA use case: LEFT JOIN is useful to find orphan records — e.g., find orders with no corresponding customer: WHERE customers.id IS NULL.',
    tags: ['SQL', 'JOIN', 'LEFT-JOIN'],
    version: null,
  },
  {
    topicSlug: 'sql-for-qa',
    text: 'Which aggregate function returns the number of rows matching a condition?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'SUM()' },
      { label: 'B', text: 'COUNT()' },
      { label: 'C', text: 'AVG()' },
      { label: 'D', text: 'MAX()' },
    ],
    correctAnswer: 'B',
    explanation: 'COUNT(*) counts all rows. COUNT(column) counts non-null values in that column. COUNT(DISTINCT column) counts unique non-null values.',
    tags: ['SQL', 'aggregate', 'COUNT'],
    version: null,
  },
  {
    topicSlug: 'sql-for-qa',
    text: 'How would you use SQL to verify that a bulk data import did not create duplicate records?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'Query to find duplicates by a unique business key (e.g., email):\n\nSELECT email, COUNT(*) as cnt\nFROM users\nGROUP BY email\nHAVING COUNT(*) > 1;\n\nIf the result set is empty, no duplicates exist.\n\nAlternatively, compare total rows vs distinct rows:\nSELECT COUNT(*) as total, COUNT(DISTINCT email) as unique_emails FROM users;\n-- If total != unique_emails, duplicates exist',
    tags: ['SQL', 'duplicates', 'data-validation'],
    version: null,
  },
  {
    topicSlug: 'sql-for-qa',
    text: 'A UNIQUE constraint in SQL prevents duplicate values in a column.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'UNIQUE constraint ensures all values in a column (or combination of columns) are distinct. Unlike PRIMARY KEY, a UNIQUE column can contain NULL (one NULL per column in most DBs).',
    tags: ['SQL', 'constraints', 'UNIQUE'],
    version: null,
  },
  {
    topicSlug: 'sql-for-qa',
    text: 'What is a subquery and give a practical QA use case for one?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'A subquery is a SELECT statement nested inside another SQL statement.\n\nQA use case — verify no orders reference a deleted product:\nSELECT * FROM orders\nWHERE product_id NOT IN (\n  SELECT id FROM products WHERE is_active = true\n);\n\nThis finds "orphan" orders pointing to inactive/deleted products — a referential integrity test without a formal FK constraint.',
    tags: ['SQL', 'subquery', 'data-validation'],
    version: null,
  },
  {
    topicSlug: 'sql-for-qa',
    text: 'The ORDER BY clause in SQL guarantees the insertion order of rows if no column is specified.',
    type: 'true_false',
    difficulty: 'medium',
    options: [],
    correctAnswer: 'false',
    explanation: 'SQL tables have no inherent row order. Without ORDER BY, the database can return rows in any order — this may vary between runs. Always include ORDER BY when testing order-dependent behavior.',
    tags: ['SQL', 'ORDER-BY'],
    version: null,
  },
  {
    topicSlug: 'sql-for-qa',
    text: 'Which SQL command is used to remove all rows from a table without logging individual row deletions?',
    type: 'multiple',
    difficulty: 'medium',
    options: [
      { label: 'A', text: 'DELETE FROM table' },
      { label: 'B', text: 'DROP TABLE table' },
      { label: 'C', text: 'TRUNCATE TABLE table' },
      { label: 'D', text: 'REMOVE FROM table' },
    ],
    correctAnswer: 'C',
    explanation: 'TRUNCATE TABLE removes all rows faster than DELETE (minimal logging, resets auto-increment counters). It cannot be rolled back in most DBs. DROP TABLE removes the table structure entirely.',
    tags: ['SQL', 'TRUNCATE', 'DELETE'],
    version: null,
  },
  {
    topicSlug: 'sql-for-qa',
    text: 'Describe three SQL queries you would use to validate data integrity after a migration.',
    type: 'open',
    difficulty: 'hard',
    options: [],
    correctAnswer: null,
    explanation: '1. Row count comparison:\nSELECT COUNT(*) FROM source_table;\nSELECT COUNT(*) FROM target_table;\n-- Counts must match\n\n2. Null check on required fields:\nSELECT COUNT(*) FROM target_table WHERE required_field IS NULL;\n-- Expect 0\n\n3. Referential integrity check:\nSELECT o.id FROM orders o\nLEFT JOIN customers c ON o.customer_id = c.id\nWHERE c.id IS NULL;\n-- Expect empty result (no orphan orders)',
    tags: ['SQL', 'data-migration', 'validation', 'integrity'],
    version: null,
  },
  {
    topicSlug: 'sql-for-qa',
    text: 'What does the LIKE operator with a "%" wildcard do in SQL?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'Matches exactly one character' },
      { label: 'B', text: 'Matches zero or more characters' },
      { label: 'C', text: 'Matches a specific number of characters' },
      { label: 'D', text: 'Performs a case-sensitive match' },
    ],
    correctAnswer: 'B',
    explanation: 'In SQL LIKE: % matches zero or more of any character; _ matches exactly one character. Example: WHERE name LIKE "Jo%" matches "John", "Jose", "Jo".',
    tags: ['SQL', 'LIKE', 'wildcards'],
    version: null,
  },
  {
    topicSlug: 'sql-for-qa',
    text: 'An INDEX on a column speeds up SELECT queries but can slow down INSERT, UPDATE, and DELETE operations.',
    type: 'true_false',
    difficulty: 'medium',
    options: [],
    correctAnswer: 'true',
    explanation: 'Indexes speed up reads by allowing the DB to find rows without a full table scan. But every write operation must also update the index, adding overhead. Test data setup scripts on large tables may be slower with many indexes.',
    tags: ['SQL', 'INDEX', 'performance'],
    version: null,
  },
  {
    topicSlug: 'sql-for-qa',
    text: 'How do you find all users who have NOT placed any orders using SQL?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'Three equivalent approaches:\n\n1. LEFT JOIN with NULL check:\nSELECT u.* FROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nWHERE o.id IS NULL;\n\n2. NOT EXISTS:\nSELECT * FROM users u\nWHERE NOT EXISTS (\n  SELECT 1 FROM orders o WHERE o.user_id = u.id\n);\n\n3. NOT IN (use carefully with NULLs):\nSELECT * FROM users\nWHERE id NOT IN (SELECT DISTINCT user_id FROM orders WHERE user_id IS NOT NULL);',
    tags: ['SQL', 'JOIN', 'NOT-EXISTS', 'data-validation'],
    version: null,
  },
  {
    topicSlug: 'sql-for-qa',
    text: 'What is the difference between DELETE and TRUNCATE in SQL?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'DELETE:\n- DML (Data Manipulation Language)\n- Can have WHERE clause to delete specific rows\n- Logs each row deletion (slower on large tables)\n- Can be rolled back within a transaction\n- Does not reset auto-increment counters\n\nTRUNCATE:\n- DDL (Data Definition Language) in most DBs\n- Removes ALL rows, no WHERE clause\n- Minimal logging (much faster)\n- Cannot be rolled back in most DBs\n- Resets auto-increment counters\n\nQA use: TRUNCATE for test data cleanup between test runs; DELETE for targeted cleanup.',
    tags: ['SQL', 'DELETE', 'TRUNCATE'],
    version: null,
  },

  // ── POSTMAN ─────────────────────────────────────────────────────────────
  {
    topicSlug: 'postman',
    text: 'In Postman, how do you reference a collection-level variable in a request URL?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: '$baseUrl' },
      { label: 'B', text: '{{baseUrl}}' },
      { label: 'C', text: '${baseUrl}' },
      { label: 'D', text: '@baseUrl' },
    ],
    correctAnswer: 'B',
    explanation: 'Postman uses double-curly-brace syntax {{variableName}} for variables at any scope (global, environment, collection, local). Example: {{baseUrl}}/api/users.',
    tags: ['postman', 'variables'],
    version: null,
  },
  {
    topicSlug: 'postman',
    text: 'Newman is a command-line tool for running Postman collections in CI/CD pipelines.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'Newman (npm install -g newman) runs Postman collections from the CLI: newman run collection.json -e environment.json --reporters cli,junit. Outputs JUnit XML for CI integration.',
    tags: ['postman', 'newman', 'CI'],
    version: null,
  },
  {
    topicSlug: 'postman',
    text: 'What is the scope hierarchy for Postman variables from highest to lowest priority?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'Priority (highest to lowest):\n1. Local variables (set with pm.variables.set in scripts, only for current request)\n2. Data variables (from CSV/JSON file in Collection Runner)\n3. Environment variables (pm.environment.set)\n4. Collection variables (pm.collectionVariables.set)\n5. Global variables (pm.globals.set)\n\nHigher priority overrides lower. Best practice: use environment variables for URLs and credentials; collection variables for shared test data.',
    tags: ['postman', 'variables', 'scope'],
    version: null,
  },
  {
    topicSlug: 'postman',
    text: 'In Postman Tests, which method do you use to parse the response body as JSON?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'pm.response.body()' },
      { label: 'B', text: 'pm.response.json()' },
      { label: 'C', text: 'JSON.parse(pm.response.text())' },
      { label: 'D', text: 'Both B and C work' },
    ],
    correctAnswer: 'D',
    explanation: 'pm.response.json() is the idiomatic Postman way to parse JSON responses. JSON.parse(pm.response.text()) also works but is more verbose. Both return a JavaScript object.',
    tags: ['postman', 'assertions', 'json'],
    version: null,
  },
  {
    topicSlug: 'postman',
    text: 'Postman environments allow you to switch between dev, staging, and production configurations.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'Environments store key-value pairs (baseUrl, tokens, etc.). Switching environments changes all {{variables}} in the collection without modifying requests. Share environment files with the team via Postman workspaces or JSON export.',
    tags: ['postman', 'environments'],
    version: null,
  },
  {
    topicSlug: 'postman',
    text: 'How do you chain Postman requests so that an ID from one response is used in the next request?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'In the Tests script of the first request, extract the ID and save it as an environment (or collection) variable:\n\nconst json = pm.response.json();\npm.environment.set("userId", json.data.id);\n\nIn the second request URL or body, reference it:\nGET {{baseUrl}}/users/{{userId}}\n\nUse the Collection Runner to run them in sequence. In Newman: newman run collection.json -e env.json',
    tags: ['postman', 'chaining', 'variables', 'workflow'],
    version: null,
  },
  {
    topicSlug: 'postman',
    text: 'What is a Postman Monitor and what is it used for?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'A Postman Monitor runs a collection on a schedule (e.g., every 5 minutes) from Postman\'s cloud servers.\n\nUse cases:\n1. Continuous API availability monitoring (uptime)\n2. Scheduled smoke test runs against production\n3. Alert on performance degradation\n\nOutputs: run results visible in Postman dashboard; can integrate with Slack/email alerts.\n\nNot a substitute for CI/CD tests — monitors are for ongoing production health checks, not pre-merge validation.',
    tags: ['postman', 'monitors', 'monitoring'],
    version: null,
  },
  {
    topicSlug: 'postman',
    text: 'In Postman, pm.test() marks a test as failed if its callback throws an exception.',
    type: 'true_false',
    difficulty: 'medium',
    options: [],
    correctAnswer: 'true',
    explanation: 'pm.test("name", () => { ... }) catches any exception thrown by the callback (including assertion failures from pm.expect / Chai) and marks the test as failed. If no exception, the test passes.',
    tags: ['postman', 'pm.test', 'assertions'],
    version: null,
  },
  {
    topicSlug: 'postman',
    text: 'What is the difference between pm.sendRequest() and a regular Postman request?',
    type: 'open',
    difficulty: 'hard',
    options: [],
    correctAnswer: null,
    explanation: 'pm.sendRequest() is an asynchronous function called from within a Pre-request Script or Tests script to make a secondary HTTP request.\n\nUse cases:\n1. Fetch an auth token in a Pre-request Script before the main request\n2. Create prerequisite test data before the request\n3. Clean up resources after the request\n\nKey difference: pm.sendRequest executes within the script context, not as a standalone collection request. It has a callback: pm.sendRequest(options, (err, res) => { ... }).',
    tags: ['postman', 'pm.sendRequest', 'scripting'],
    version: null,
  },
  {
    topicSlug: 'postman',
    text: 'Postman allows generating code snippets for requests in languages like curl, Python, and JavaScript.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'Click "Code" (</>) button in Postman to generate equivalent code snippets in curl, Python requests, JavaScript fetch/axios, Java OkHttp, and more. Useful for sharing API calls or embedding them in automation code.',
    tags: ['postman', 'code-generation'],
    version: null,
  },
  {
    topicSlug: 'postman',
    text: 'How would you use Postman to test a paginated API endpoint?',
    type: 'open',
    difficulty: 'hard',
    options: [],
    correctAnswer: null,
    explanation: 'Use the Collection Runner with a data file, or use pm.setNextRequest() for looping:\n\nIn Tests script:\nconst json = pm.response.json();\nconst page = pm.environment.get("page") || 1;\n\n// Assert current page\npm.test(`Page ${page} has items`, () => {\n  pm.expect(json.data.length).to.be.above(0);\n});\n\n// If more pages exist, loop\nif (json.nextPage) {\n  pm.environment.set("page", page + 1);\n  pm.setNextRequest("Get Users"); // self-reference\n} else {\n  pm.setNextRequest(null); // stop loop\n}',
    tags: ['postman', 'pagination', 'pm.setNextRequest'],
    version: null,
  },
  {
    topicSlug: 'postman',
    text: 'Which Postman feature lets you run a collection with different data sets from a CSV or JSON file?',
    type: 'multiple',
    difficulty: 'medium',
    options: [
      { label: 'A', text: 'Postman Monitor' },
      { label: 'B', text: 'Collection Runner with data file' },
      { label: 'C', text: 'Environment switcher' },
      { label: 'D', text: 'Postman Flows' },
    ],
    correctAnswer: 'B',
    explanation: 'Collection Runner accepts a data file (CSV or JSON). Each row/object is one iteration. Variables from the file are available as {{variableName}} in requests and pm.iterationData.get("variableName") in scripts.',
    tags: ['postman', 'collection-runner', 'data-driven'],
    version: null,
  },
  {
    topicSlug: 'postman',
    text: 'Explain what Postman Mock Servers are and give a use case.',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'A Postman Mock Server returns predefined example responses for matching requests, without a real backend.\n\nHow it works: save example responses to your collection requests → create a mock server → Postman hosts it at a URL.\n\nUse cases:\n1. Frontend development before the API is built\n2. Testing error scenarios (simulate 500, 429) without triggering them in real APIs\n3. Offline API testing\n4. Demos and prototyping\n\nRequests to the mock are matched by method, path, and optionally query params/headers.',
    tags: ['postman', 'mock-servers', 'mocking'],
    version: null,
  },

  // ── JAVA BASICS ──────────────────────────────────────────────────────────
  {
    topicSlug: 'java-basics',
    text: 'In Java, what is the difference between == and .equals() when comparing Strings?',
    type: 'open',
    difficulty: 'easy',
    options: [],
    correctAnswer: null,
    explanation: '== compares object REFERENCES (memory addresses).\n.equals() compares object VALUES (content).\n\nFor String:\nString a = new String("hello");\nString b = new String("hello");\na == b       → false (different objects)\na.equals(b) → true  (same content)\n\nBut: String literals from the pool may be == true due to interning.\n\nRule: always use .equals() for value comparison. == for reference/null check.',
    tags: ['Java', 'String', 'equals'],
    version: null,
  },
  {
    topicSlug: 'java-basics',
    text: 'In Java, a final variable cannot be reassigned after initialization.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'final modifier on a variable means it can only be assigned once. For primitives: value cannot change. For objects: the reference cannot change, but the object\'s internal state can still be mutated.',
    tags: ['Java', 'final', 'variables'],
    version: null,
  },
  {
    topicSlug: 'java-basics',
    text: 'Which Java collection maintains insertion order and allows duplicate elements?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'HashSet' },
      { label: 'B', text: 'TreeSet' },
      { label: 'C', text: 'ArrayList' },
      { label: 'D', text: 'HashMap' },
    ],
    correctAnswer: 'C',
    explanation: 'ArrayList implements List — ordered by index, allows duplicates. HashSet and TreeSet are Sets — no duplicates. HashMap is a key-value map.',
    tags: ['Java', 'collections', 'ArrayList'],
    version: null,
  },
  {
    topicSlug: 'java-basics',
    text: 'What is the difference between checked and unchecked exceptions in Java?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'Checked exceptions: must be declared with "throws" or caught with try/catch. Compiler enforces handling. Examples: IOException, SQLException.\n\nUnchecked exceptions (RuntimeException subclasses): do not need to be declared. Examples: NullPointerException, ArrayIndexOutOfBoundsException.\n\nFor QA automation: most Selenium/Playwright exceptions are unchecked (NoSuchElementException, StaleElementReferenceException), so you can choose whether to catch them or let them fail the test.',
    tags: ['Java', 'exceptions', 'checked', 'unchecked'],
    version: null,
  },
  {
    topicSlug: 'java-basics',
    text: 'In Java, an interface can contain default method implementations since Java 8.',
    type: 'true_false',
    difficulty: 'medium',
    options: [],
    correctAnswer: 'true',
    explanation: 'Java 8 introduced default methods in interfaces (default keyword). This allows adding new methods to interfaces without breaking existing implementations. Also added static methods in interfaces.',
    tags: ['Java', 'interfaces', 'Java8'],
    version: 'Java 8+',
  },
  {
    topicSlug: 'java-basics',
    text: 'What is method overloading vs method overriding in Java?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'Overloading: same method name, different parameters (type, number, or order) in the SAME class. Resolved at compile time (static polymorphism).\n\nOverriding: subclass provides a different implementation of an inherited method with the SAME signature. Resolved at runtime (dynamic polymorphism). Requires @Override annotation for safety.\n\nExample: Calculator.add(int, int) and Calculator.add(double, double) = overloading. Animal.speak() overridden in Dog and Cat = overriding.',
    tags: ['Java', 'OOP', 'overloading', 'overriding'],
    version: null,
  },
  {
    topicSlug: 'java-basics',
    text: 'Which access modifier in Java makes a member accessible only within the same class?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'protected' },
      { label: 'B', text: 'package-private (no modifier)' },
      { label: 'C', text: 'private' },
      { label: 'D', text: 'public' },
    ],
    correctAnswer: 'C',
    explanation: 'private: only within the same class. No modifier (package-private): same class + same package. protected: same class + package + subclasses. public: everywhere.',
    tags: ['Java', 'access-modifiers', 'encapsulation'],
    version: null,
  },
  {
    topicSlug: 'java-basics',
    text: 'In Java, ArrayList is thread-safe.',
    type: 'true_false',
    difficulty: 'medium',
    options: [],
    correctAnswer: 'false',
    explanation: 'ArrayList is NOT thread-safe. For thread-safe lists use: Collections.synchronizedList(new ArrayList<>()), or CopyOnWriteArrayList (from java.util.concurrent). Vector is thread-safe but legacy and rarely used.',
    tags: ['Java', 'collections', 'thread-safety'],
    version: null,
  },
  {
    topicSlug: 'java-basics',
    text: 'What is the purpose of the @Override annotation in Java?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'Forces the compiler to generate a new method' },
      { label: 'B', text: 'Tells the compiler to verify this method overrides a parent method' },
      { label: 'C', text: 'Prevents the method from being overridden in subclasses' },
      { label: 'D', text: 'Marks the method as deprecated' },
    ],
    correctAnswer: 'B',
    explanation: '@Override is a marker annotation that tells the compiler: "this method must override a method from the parent class or interface." If it doesn\'t, compilation fails — preventing typos in method names from silently creating new methods.',
    tags: ['Java', 'annotations', 'Override'],
    version: null,
  },
  {
    topicSlug: 'java-basics',
    text: 'What is the purpose of try-with-resources in Java and why is it relevant for QA automation?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'try-with-resources (Java 7+) automatically closes resources that implement AutoCloseable when the try block exits, even if an exception is thrown.\n\nSyntax:\ntry (Connection conn = DriverManager.getConnection(url)) {\n  // use conn\n} // conn.close() called automatically\n\nQA relevance:\n- Database connections in test setup/teardown: ensures connections are always closed\n- FileReader for reading test data files\n- Prevents resource leaks that could cause test environment issues after many test runs',
    tags: ['Java', 'try-with-resources', 'AutoCloseable'],
    version: 'Java 7+',
  },
  {
    topicSlug: 'java-basics',
    text: 'Java\'s HashMap allows null keys.',
    type: 'true_false',
    difficulty: 'medium',
    options: [],
    correctAnswer: 'true',
    explanation: 'HashMap allows one null key and multiple null values. Hashtable (the legacy version) does not allow null keys or values. TreeMap also does not allow null keys (throws NullPointerException).',
    tags: ['Java', 'HashMap', 'null'],
    version: null,
  },
  {
    topicSlug: 'java-basics',
    text: 'Explain the four pillars of OOP in Java with a brief description of each.',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: '1. Encapsulation: bundling data (fields) and methods that operate on it into a class, hiding internal state with private + getters/setters.\n\n2. Inheritance: a subclass extends a parent class, reusing and extending its behavior. Java uses extends. Promotes code reuse.\n\n3. Polymorphism: same method name behaves differently based on the object type at runtime (overriding) or compile time (overloading).\n\n4. Abstraction: hiding implementation details, exposing only what\'s necessary. Achieved with abstract classes and interfaces.\n\nQA relevance: POM uses encapsulation; base test classes use inheritance; test frameworks use polymorphism.',
    tags: ['Java', 'OOP', 'pillars'],
    version: null,
  },
  {
    topicSlug: 'java-basics',
    text: 'Which Java 8 feature allows passing behavior as a parameter to a method?',
    type: 'multiple',
    difficulty: 'medium',
    options: [
      { label: 'A', text: 'Generics' },
      { label: 'B', text: 'Lambda expressions' },
      { label: 'C', text: 'Static imports' },
      { label: 'D', text: 'Annotations' },
    ],
    correctAnswer: 'B',
    explanation: 'Lambda expressions (Java 8) allow you to pass functional behavior as a parameter. They implement functional interfaces (interfaces with a single abstract method). Example: list.sort((a, b) -> a.compareTo(b));',
    tags: ['Java8', 'lambda', 'functional'],
    version: 'Java 8+',
  },
  {
    topicSlug: 'java-basics',
    text: 'What is the difference between HashMap and LinkedHashMap?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'HashMap: no guaranteed iteration order. Keys are stored based on their hash code. O(1) average for get/put.\n\nLinkedHashMap: maintains insertion order (or access order if constructed with accessOrder=true). Slightly more memory overhead due to doubly linked list.\n\nUse LinkedHashMap when you need predictable iteration order (e.g., ordered JSON serialization in tests). Use HashMap when order doesn\'t matter and you want maximum performance.',
    tags: ['Java', 'collections', 'HashMap', 'LinkedHashMap'],
    version: null,
  },

  // ── AGILE / SCRUM ────────────────────────────────────────────────────────
  {
    topicSlug: 'agile-scrum',
    text: 'What is the QA engineer\'s primary responsibility during a Sprint in Scrum?',
    type: 'open',
    difficulty: 'easy',
    options: [],
    correctAnswer: null,
    explanation: 'QA in Scrum is not a "gate at the end" — it\'s a continuous activity:\n\n1. Sprint Planning: clarify acceptance criteria, flag testability issues, estimate testing effort\n2. During Sprint: write and run tests alongside development (not after)\n3. Refinement: review stories for completeness of AC, identify edge cases\n4. Sprint Review: demo tested features, validate against AC\n5. Retrospective: identify process improvements for testing\n\nGoal: all PBIs meet the Definition of Done (including automated tests) before the Sprint ends.',
    tags: ['agile', 'scrum', 'QA-role'],
    version: null,
  },
  {
    topicSlug: 'agile-scrum',
    text: 'In Scrum, the Product Owner is responsible for creating and prioritizing the Product Backlog.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'The Product Owner owns the Product Backlog — adding, ordering, and clarifying items to maximize value. The Development Team (including QA) estimates effort but the PO sets priority.',
    tags: ['scrum', 'product-owner', 'backlog'],
    version: null,
  },
  {
    topicSlug: 'agile-scrum',
    text: 'What is the purpose of a Definition of Done (DoD) in Scrum?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'The Definition of Done is a shared understanding of what "complete" means for any increment. It\'s a checklist that every PBI must satisfy before being declared done.\n\nTypical DoD items from a QA perspective:\n- Unit tests written and passing\n- Integration tests passing\n- Acceptance criteria verified\n- Automated regression suite updated\n- No critical bugs open\n- Code reviewed\n- Deployed to staging\n\nImportance: prevents "it works on my machine" and ensures consistent quality across all stories.',
    tags: ['scrum', 'DoD', 'quality'],
    version: null,
  },
  {
    topicSlug: 'agile-scrum',
    text: 'Which Scrum ceremony is specifically used to inspect the increment and adapt the Product Backlog?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'Sprint Retrospective' },
      { label: 'B', text: 'Daily Scrum' },
      { label: 'C', text: 'Sprint Review' },
      { label: 'D', text: 'Sprint Planning' },
    ],
    correctAnswer: 'C',
    explanation: 'Sprint Review (Demo): stakeholders review the increment, the PO adapts the backlog based on feedback. Sprint Retrospective focuses on the team process, not the product.',
    tags: ['scrum', 'ceremonies', 'sprint-review'],
    version: null,
  },
  {
    topicSlug: 'agile-scrum',
    text: 'In Kanban, Work In Progress (WIP) limits are used to reduce context-switching and improve flow.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'WIP limits cap the number of items allowed in each column. This exposes bottlenecks, forces collaboration to clear blockers, and prevents the team from starting more work than can be finished.',
    tags: ['kanban', 'WIP', 'flow'],
    version: null,
  },
  {
    topicSlug: 'agile-scrum',
    text: 'What are Acceptance Criteria (AC) and how should a QA use them?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'Acceptance Criteria define the conditions that a user story must meet to be accepted by the Product Owner — specific, testable conditions.\n\nGood AC format (Given/When/Then — Gherkin):\nGiven a user on the login page\nWhen they enter valid credentials\nThen they should be redirected to the dashboard\n\nQA uses AC to:\n1. Derive test cases (happy path and edge cases)\n2. Identify missing or ambiguous requirements early (refinement)\n3. Determine pass/fail for testing\n4. Write automated tests in BDD frameworks (Cucumber, SpecFlow)',
    tags: ['agile', 'acceptance-criteria', 'BDD', 'Gherkin'],
    version: null,
  },
  {
    topicSlug: 'agile-scrum',
    text: 'Technical debt refers to the implied cost of future rework caused by choosing a quick solution now over a better approach.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'Technical debt (Ward Cunningham) accumulates when shortcuts are taken under pressure. Left unmanaged, it slows velocity over time. QA should flag testing shortcuts (e.g., skipped automation) as explicit tech debt in the backlog.',
    tags: ['agile', 'technical-debt'],
    version: null,
  },
  {
    topicSlug: 'agile-scrum',
    text: 'What is the difference between velocity and throughput in Agile metrics?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'Velocity: the sum of story points completed per Sprint. Used for planning future sprints ("we average 40 points per sprint").\n\nThroughput: the number of work items (stories, tasks) completed per time period, regardless of size. Used in Kanban and flow-based metrics.\n\nKindamental difference: velocity depends on story point estimation (subjective); throughput counts items (objective).\n\nQA relevance: track testing throughput separately to identify QA as a bottleneck.',
    tags: ['agile', 'metrics', 'velocity', 'throughput'],
    version: null,
  },
  {
    topicSlug: 'agile-scrum',
    text: 'A User Story should follow the INVEST criteria. What does INVEST stand for?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'INVEST (Bill Wake):\n- Independent: can be developed in any order without hard dependencies\n- Negotiable: details can be discussed and adjusted\n- Valuable: delivers value to users or the business\n- Estimable: team can estimate the effort\n- Small: fits within one sprint\n- Testable: has clear, measurable acceptance criteria\n\nQA uses INVEST to flag stories in refinement that lack testability (T) or have unclear acceptance criteria.',
    tags: ['agile', 'INVEST', 'user-stories'],
    version: null,
  },
  {
    topicSlug: 'agile-scrum',
    text: 'In Scrum, the Daily Standup should last no longer than 15 minutes.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'The Daily Scrum is a 15-minute time-boxed event for the Development Team to synchronize activities and plan for the next 24 hours. It\'s not a status report — it\'s a planning session.',
    tags: ['scrum', 'daily-standup', 'time-box'],
    version: null,
  },
  {
    topicSlug: 'agile-scrum',
    text: 'What is a Sprint Retrospective and what format can a QA use to make it more effective?',
    type: 'open',
    difficulty: 'medium',
    options: [],
    correctAnswer: null,
    explanation: 'Sprint Retrospective: inspect how the last Sprint went regarding people, relationships, process, and tools. Identify improvements for next Sprint.\n\nCommon format — Start / Stop / Continue:\n- Start: what should we begin doing? (e.g., automate smoke tests in CI)\n- Stop: what is hurting us? (e.g., manual regression every sprint)\n- Continue: what is working? (e.g., pair testing new features)\n\nQA-specific improvements to raise:\n- Moving testing left (spec review earlier)\n- Dedicated automation time per sprint\n- Bug bash sessions before release\n- Improving test data management',
    tags: ['scrum', 'retrospective', 'improvement'],
    version: null,
  },
  {
    topicSlug: 'agile-scrum',
    text: 'BDD (Behavior-Driven Development) bridges the communication gap between technical and non-technical team members.',
    type: 'true_false',
    difficulty: 'easy',
    options: [],
    correctAnswer: 'true',
    explanation: 'BDD uses a shared language (Given/When/Then — Gherkin) that both business stakeholders and developers/QAs can read and write. Tools like Cucumber and SpecFlow execute these specifications as automated tests.',
    tags: ['BDD', 'Gherkin', 'Cucumber'],
    version: null,
  },
  {
    topicSlug: 'agile-scrum',
    text: 'What is a Scrum of Scrums and when is it used?',
    type: 'open',
    difficulty: 'hard',
    options: [],
    correctAnswer: null,
    explanation: 'A Scrum of Scrums is a coordination technique for scaling Scrum across multiple teams working on the same product.\n\nStructure: one representative from each Scrum team meets periodically (daily or a few times per week) to synchronize across team boundaries.\n\nAgenda (modified standup):\n- What did our team do since last meeting that affects other teams?\n- What will we do that might affect other teams?\n- Any impediments between teams?\n\nQA relevance: coordinate shared test environments, integration testing ownership, and release readiness across teams.',
    tags: ['agile', 'scaling', 'Scrum-of-Scrums'],
    version: null,
  },
  {
    topicSlug: 'agile-scrum',
    text: 'Which Scrum artifact represents the work identified for the current Sprint?',
    type: 'multiple',
    difficulty: 'easy',
    options: [
      { label: 'A', text: 'Product Backlog' },
      { label: 'B', text: 'Sprint Backlog' },
      { label: 'C', text: 'Sprint Goal' },
      { label: 'D', text: 'Increment' },
    ],
    correctAnswer: 'B',
    explanation: 'Sprint Backlog: the set of Product Backlog Items selected for the Sprint + a plan for delivering them. The Development Team owns it. Product Backlog is the full ordered list of everything needed. Increment is the product of all Sprint work.',
    tags: ['scrum', 'artifacts', 'sprint-backlog'],
    version: null,
  },
]
