/**
 * scripts/seed-data-volume.ts
 *
 * Volume expansion for exam mode:
 *  - API Testing  (+45 → 60 total)
 *  - CI/CD        (+47 → 60 total)
 *  - SQL for QA   (+46 → 60 total)
 *
 * Mix per topic: ~60% multiple choice, ~25% true/false, ~15% open.
 * Includes hard scorable questions and a balanced true/false split.
 */

import type { ExtraQuestionSeed } from './seed-data-extra'

type Diff = 'easy' | 'medium' | 'hard'
type Label = 'A' | 'B' | 'C' | 'D'

const LABELS: Label[] = ['A', 'B', 'C', 'D']

const m = (
  topicSlug: string, difficulty: Diff, text: string,
  opts: [string, string, string, string], correct: Label,
  explanation: string, tags: string[] = []
): ExtraQuestionSeed => ({
  topicSlug, type: 'multiple', difficulty, text,
  options: opts.map((t, i) => ({ label: LABELS[i], text: t })),
  correctAnswer: correct, explanation, tags, version: null,
})

const tf = (
  topicSlug: string, difficulty: Diff, text: string,
  correct: boolean, explanation: string, tags: string[] = []
): ExtraQuestionSeed => ({
  topicSlug, type: 'true_false', difficulty, text,
  options: [], correctAnswer: String(correct), explanation, tags, version: null,
})

const op = (
  topicSlug: string, difficulty: Diff, text: string,
  explanation: string, tags: string[] = []
): ExtraQuestionSeed => ({
  topicSlug, type: 'open', difficulty, text,
  options: [], correctAnswer: null, explanation, tags, version: null,
})

const API = 'api-testing'
const CI = 'cicd'
const SQL = 'sql-for-qa'

// ═══════════════════════════════════════════════════════════════════════
// API TESTING — 27 multiple, 11 true/false, 7 open (45)
// ═══════════════════════════════════════════════════════════════════════

const API_QUESTIONS: ExtraQuestionSeed[] = [
  // ── multiple / easy ──
  m(API, 'easy', 'Which HTTP status code indicates that a resource was successfully created?',
    ['200 OK', '201 Created', '204 No Content', '301 Moved Permanently'], 'B',
    '201 Created is the standard response for a successful POST that creates a resource. 200 is generic success and 204 means success with no body.', ['http', 'status-codes']),
  m(API, 'easy', 'Which HTTP method should be used to retrieve data without modifying it?',
    ['POST', 'PUT', 'GET', 'PATCH'], 'C',
    'GET is the read-only method. It should be safe (no side effects) and idempotent.', ['http', 'methods']),
  m(API, 'easy', 'What does a 404 status code mean?',
    ['The requested resource was not found', 'The user is not authenticated', 'The server crashed', 'Access to the resource is forbidden'], 'A',
    '404 Not Found means the server cannot find the requested resource. 401 is unauthenticated, 403 is forbidden, 5xx are server errors.', ['http', 'status-codes']),
  m(API, 'easy', 'Which status code class represents client errors?',
    ['2xx', '3xx', '4xx', '5xx'], 'C',
    '4xx codes indicate the client did something wrong (bad request, unauthorized, not found). 5xx codes indicate server-side failures.', ['http', 'status-codes']),
  m(API, 'easy', 'Which format is most commonly used for REST API request and response bodies today?',
    ['XML', 'JSON', 'CSV', 'Plain text'], 'B',
    'JSON is the de facto standard for REST APIs: lightweight, human readable and natively supported by JavaScript.', ['rest', 'json']),
  m(API, 'easy', 'Which header tells the server the media type of the request body being sent?',
    ['Accept', 'Authorization', 'Content-Type', 'Cache-Control'], 'C',
    'Content-Type describes the body you are sending (e.g. application/json). Accept tells the server what format you want back.', ['http', 'headers']),
  m(API, 'easy', 'Which HTTP method is typically used to fully replace an existing resource?',
    ['PUT', 'PATCH', 'POST', 'OPTIONS'], 'A',
    'PUT replaces the entire resource with the payload. PATCH applies a partial update. POST creates new resources.', ['http', 'methods']),
  m(API, 'easy', 'In API testing, what is an endpoint?',
    ['The database table behind the API', 'The JSON schema of a response', 'The test environment URL only', 'A specific URL path where an API receives requests'], 'D',
    'An endpoint is a URL path (e.g. /api/users) combined with an HTTP method where the API exposes an operation.', ['rest', 'basics']),

  // ── multiple / medium ──
  m(API, 'medium', 'What is the difference between a 401 and a 403 response?',
    ['401 is a server error; 403 is a client error', '401 means not authenticated; 403 means authenticated but not allowed', '401 means the resource moved; 403 means it was deleted', 'They are interchangeable'], 'B',
    '401 Unauthorized actually means "unauthenticated" (missing or invalid credentials). 403 Forbidden means the identity is known but lacks permission.', ['http', 'auth', 'status-codes']),
  m(API, 'medium', 'Which set of HTTP methods is idempotent?',
    ['GET, PUT, DELETE', 'POST, PUT, PATCH', 'POST only', 'GET and POST'], 'A',
    'GET, PUT and DELETE are idempotent: repeating the request leaves the server in the same state. POST is not, and PATCH is not guaranteed to be.', ['http', 'idempotency']),
  m(API, 'medium', 'What is the purpose of the Accept header in a request?',
    ['To authenticate the client', 'To compress the payload', 'To tell the server which response format the client wants', 'To define the body media type'], 'C',
    'Accept performs content negotiation: the client declares formats it can handle (e.g. application/json) and the server responds accordingly.', ['http', 'headers']),
  m(API, 'medium', 'In REST, what does statelessness mean?',
    ['Each request must contain all the information needed; the server stores no client session between requests', 'The API cannot use a database', 'Responses never change', 'The client cannot store cookies'], 'A',
    'Statelessness means the server does not keep client session state between requests. Every request is self-contained, which improves scalability.', ['rest', 'architecture']),
  m(API, 'medium', 'Which status code is most appropriate for a successful DELETE that returns no body?',
    ['200 OK', '204 No Content', '202 Accepted', '410 Gone'], 'B',
    '204 No Content signals success without a response body, which fits DELETE. 200 with a body is also acceptable but 204 is the cleanest fit.', ['http', 'status-codes']),
  m(API, 'medium', 'What is contract testing?',
    ['Load testing the API under contract SLAs', 'Testing legal compliance of the API', 'Manually comparing API docs against code', 'Verifying that the API provider and its consumers agree on the request/response structure'], 'D',
    'Contract tests verify that the provider response matches what consumers expect (fields, types, status codes), catching breaking changes early.', ['contract-testing']),
  m(API, 'medium', 'Which tool is specifically designed for consumer-driven contract testing?',
    ['Pact', 'JMeter', 'Cypress', 'Lighthouse'], 'A',
    'Pact implements consumer-driven contract testing: consumers define expectations and providers verify against them.', ['contract-testing', 'tools']),
  m(API, 'medium', 'What is the main reason for versioning an API (e.g. /v1/users)?',
    ['To improve performance', 'To make URLs shorter', 'To introduce breaking changes without breaking existing clients', 'To hide endpoints from attackers'], 'C',
    'Versioning lets the provider evolve the API while old clients keep working against the previous version.', ['rest', 'versioning']),
  m(API, 'medium', 'In REST Assured, which method starts the request specification in the given/when/then syntax?',
    ['request()', 'given()', 'init()', 'spec()'], 'B',
    'REST Assured uses given() for setup (headers, params, body), when() for the action and then() for assertions.', ['rest-assured', 'java']),
  m(API, 'medium', 'What does a 429 status code indicate?',
    ['The client has sent too many requests and is being rate limited', 'The request payload is too large', 'The API version is deprecated', 'The session expired'], 'A',
    '429 Too Many Requests is returned when the client exceeds a rate limit. Tests should verify it and check the Retry-After header.', ['http', 'rate-limiting']),
  m(API, 'medium', 'Where should a bearer token be sent?',
    ['In the X-Api-Key header', 'In the URL path', 'In the request body', 'In the Authorization header with the Bearer scheme'], 'D',
    'The standard is Authorization: Bearer <token>. Tokens in URLs leak through logs and browser history.', ['auth', 'headers']),
  m(API, 'medium', 'What is the difference between PUT and PATCH?',
    ['PUT is for creating only; PATCH is for deleting', 'PUT replaces the whole resource; PATCH applies a partial update', 'PATCH is idempotent by definition; PUT is not', 'There is no difference'], 'B',
    'PUT sends the complete new representation. PATCH sends only the fields to change. Missing fields in a PUT are typically reset.', ['http', 'methods']),

  // ── multiple / hard ──
  m(API, 'hard', 'DELETE /users/7 returns 204, and calling it again returns 404. Is DELETE still idempotent?',
    ['Yes — the server state is the same after one or many calls, even if the status code differs', 'No — different status codes break idempotency', 'Only if the second call also returns 204', 'DELETE was never idempotent'], 'A',
    'Idempotency is about server state, not identical responses. After any number of DELETE calls the resource is gone, so DELETE remains idempotent.', ['http', 'idempotency']),
  m(API, 'hard', 'What does HATEOAS mean in a REST API?',
    ['Responses are always cached at the edge', 'All endpoints require hypertext content types', 'Responses include links that tell the client which actions are available next', 'The API is documented with OpenAPI'], 'C',
    'Hypermedia As The Engine Of Application State: the response embeds links (e.g. next, cancel) so clients navigate the API dynamically.', ['rest', 'architecture']),
  m(API, 'hard', 'Which OAuth 2.0 grant type is recommended for machine-to-machine (server-to-server) communication?',
    ['Authorization code', 'Client credentials', 'Implicit', 'Resource owner password'], 'B',
    'Client credentials is designed for M2M: the client authenticates with its own credentials, no user involved. Implicit and password grants are deprecated.', ['oauth', 'auth']),
  m(API, 'hard', 'What is the purpose of the ETag header?',
    ['It enables caching validation and optimistic concurrency control', 'It encrypts the response body', 'It identifies the API version', 'It tracks the user session'], 'A',
    'ETag is a resource fingerprint. Clients send If-None-Match (cache validation, 304) or If-Match (detect concurrent updates, 412).', ['http', 'caching', 'headers']),
  m(API, 'hard', 'Which statement about GraphQL vs REST is true?',
    ['GraphQL requires one endpoint per resource', 'GraphQL cannot return JSON', 'REST always outperforms GraphQL', 'GraphQL exposes a single endpoint and lets the client specify exactly which fields it needs'], 'D',
    'GraphQL uses one endpoint and a query language so clients avoid over-fetching and under-fetching. REST exposes many endpoints with fixed responses.', ['graphql', 'rest']),
  m(API, 'hard', 'What is the main advantage of cursor-based pagination over offset-based pagination?',
    ['It is easier to implement', 'Results stay consistent when rows are inserted or deleted between pages', 'It allows jumping to any arbitrary page', 'It works without sorting'], 'B',
    'Offset pagination can skip or duplicate items when data changes between requests. Cursors anchor to the last seen item, keeping pages stable.', ['rest', 'pagination']),
  m(API, 'hard', 'Why validate API responses against a JSON Schema in automated tests?',
    ['It replaces the need for status code checks', 'It guarantees the database is consistent', 'It catches structural regressions (missing fields, wrong types) without asserting every value', 'It makes the tests run faster'], 'C',
    'Schema validation asserts the response shape and types in one step, catching breaking changes that individual field assertions might miss.', ['json-schema', 'automation']),

  // ── true/false ──
  tf(API, 'easy', 'A 500 status code means the client sent an invalid request.', false,
    'False. 5xx codes are server-side errors. Client errors are the 4xx class (e.g. 400 Bad Request).', ['http', 'status-codes']),
  tf(API, 'easy', 'GET requests should not change server state.', true,
    'True. GET is defined as safe: it must be read-only. State changes belong to POST, PUT, PATCH or DELETE.', ['http', 'methods']),
  tf(API, 'easy', 'POST is an idempotent HTTP method.', false,
    'False. Repeating a POST typically creates a new resource each time. GET, PUT and DELETE are the idempotent ones.', ['http', 'idempotency']),
  tf(API, 'medium', 'The Authorization header is commonly used to send credentials such as bearer tokens.', true,
    'True. Schemes like Bearer, Basic and Digest all travel in the Authorization header.', ['auth', 'headers']),
  tf(API, 'medium', 'REST APIs must always use JSON.', false,
    'False. REST is format-agnostic: XML, plain text or any media type is valid. JSON is just the most common choice.', ['rest', 'json']),
  tf(API, 'medium', 'A 204 response should not include a response body.', true,
    'True. 204 No Content explicitly means there is no body. Sending one violates the HTTP spec.', ['http', 'status-codes']),
  tf(API, 'medium', 'PUT and PATCH behave identically.', false,
    'False. PUT replaces the full resource; PATCH modifies only the provided fields.', ['http', 'methods']),
  tf(API, 'medium', 'Status code 302 indicates a client error.', false,
    'False. 3xx codes are redirections. 302 Found redirects the client to another URL temporarily.', ['http', 'status-codes']),
  tf(API, 'hard', 'Idempotent means that multiple identical requests leave the server in the same state as a single request.', true,
    'True. That is the definition. The responses may differ (e.g. 204 then 404 for DELETE), but the resulting state is the same.', ['http', 'idempotency']),
  tf(API, 'hard', 'In OAuth 2.0, the implicit grant is currently the recommended flow for single-page applications.', false,
    'False. The implicit grant is deprecated. The current recommendation for SPAs is authorization code with PKCE.', ['oauth', 'auth']),
  tf(API, 'hard', 'Contract tests can catch breaking API changes before they reach integration environments.', true,
    'True. Provider-side contract verification runs in CI against consumer expectations, failing the build before deployment.', ['contract-testing']),

  // ── open ──
  op(API, 'easy', 'What is the difference between SOAP and REST?',
    'SOAP is a strict protocol: XML-only envelopes, WSDL contracts, built-in standards for security and transactions. REST is an architectural style: any format (usually JSON), uses standard HTTP verbs and status codes, lighter and easier to consume. REST dominates public web APIs; SOAP survives in enterprise/legacy integrations.', ['soap', 'rest']),
  op(API, 'medium', 'Explain the difference between authentication and authorization in the context of APIs.',
    'Authentication verifies WHO you are (credentials, tokens, certificates) — failure returns 401. Authorization verifies WHAT you can do (roles, scopes, permissions) — failure returns 403. Example: a valid token (authenticated) of a regular user calling an admin endpoint gets 403.', ['auth']),
  op(API, 'medium', 'How would you test an endpoint that creates a user (POST /users)? List the cases you would cover.',
    'Happy path: valid payload returns 201 with the created user and correct schema; verify persistence with a GET or DB query. Negative: missing required fields (400), invalid email format, duplicate email (409), invalid/missing token (401), wrong content type. Edge: max field lengths, special/unicode characters, extra unexpected fields. Security: SQL injection and XSS payloads in fields, password not returned in response.', ['test-design', 'crud']),
  op(API, 'medium', 'What is negative testing for APIs? Give concrete examples.',
    'Negative testing sends invalid, unexpected or malicious input to verify the API fails safely with the right status and message, without leaking internals. Examples: malformed JSON (400), wrong data types, missing auth (401), nonexistent resource ID (404), unsupported method (405), oversized payload (413), injection strings, expired tokens.', ['test-design', 'negative-testing']),
  op(API, 'hard', 'How would you test rate limiting on an API?',
    'Read the spec (limit, window, scope per user/IP/key). Send requests up to the limit and assert success; the next request must return 429 with Retry-After or X-RateLimit-* headers. Verify the counter resets after the window, that limits are isolated per client, and that retrying after Retry-After succeeds. Automate with a loop or load tool, and test boundary exactly at limit and limit+1.', ['rate-limiting', 'test-design']),
  op(API, 'hard', 'A new API version introduces breaking changes. What is your testing strategy?',
    'Inventory the breaking changes from the changelog/diff of the OpenAPI spec. Keep the old version test suite running against /v1 to prove backward compatibility is intact. Build a new suite for /v2 covering changed contracts. Add contract tests with consumer expectations. Verify deprecation headers/warnings on v1, parallel-run both versions in staging, and test the migration path with real consumer payloads.', ['versioning', 'strategy']),
  op(API, 'hard', 'How would you structure the API test layers in an automation framework?',
    'Bottom: schema/contract tests per endpoint (fast, run on every commit). Middle: functional tests per endpoint covering positive/negative cases with isolated test data (setup/teardown via API or DB). Top: business flow tests chaining endpoints (create → update → verify → delete). Separate smoke subset for deployments. Shared layers: client wrapper, auth handling, test data builders, environment config. Keep tests independent and parallelizable.', ['framework', 'strategy']),
]

// ═══════════════════════════════════════════════════════════════════════
// CI/CD — 28 multiple, 12 true/false, 7 open (47)
// ═══════════════════════════════════════════════════════════════════════

const CI_QUESTIONS: ExtraQuestionSeed[] = [
  // ── multiple / easy ──
  m(CI, 'easy', 'What does CI stand for?',
    ['Code Inspection', 'Continuous Integration', 'Centralized Infrastructure', 'Component Isolation'], 'B',
    'Continuous Integration: developers merge small changes frequently, and each merge triggers an automated build and test run.', ['ci', 'basics']),
  m(CI, 'easy', 'What is the main goal of Continuous Integration?',
    ['Detect integration problems early by building and testing every change automatically', 'Deploy to production on every commit', 'Eliminate the need for code review', 'Replace manual testing entirely'], 'A',
    'CI catches conflicts and regressions within minutes of a merge instead of weeks later during a big-bang integration.', ['ci', 'basics']),
  m(CI, 'easy', 'Where do GitHub Actions workflow files live in a repository?',
    ['/actions/', '/ci/workflows/', '.github/workflows/', '.workflows/github/'], 'C',
    'Workflows are YAML files stored under .github/workflows/ in the repository.', ['github-actions']),
  m(CI, 'easy', 'What is the conventional name of the file that defines a Jenkins pipeline as code?',
    ['jenkins.yml', 'pipeline.xml', 'build.jenkins', 'Jenkinsfile'], 'D',
    'A Jenkinsfile (Groovy syntax) defines the pipeline and is version-controlled with the application code.', ['jenkins']),
  m(CI, 'easy', 'What are the two common meanings of CD?',
    ['Continuous Delivery and Continuous Deployment', 'Code Deployment and Code Delivery', 'Continuous Development and Continuous Design', 'Container Deployment and Cloud Distribution'], 'A',
    'Continuous Delivery keeps every build releasable with a manual approval to deploy; Continuous Deployment releases automatically with no manual gate.', ['cd', 'basics']),
  m(CI, 'easy', 'Which GitHub Actions event triggers a workflow when someone opens a pull request?',
    ['push', 'pull_request', 'merge', 'commit'], 'B',
    'The pull_request event fires on PR open, sync and reopen. push fires on commits to branches.', ['github-actions']),
  m(CI, 'easy', 'What is a build artifact?',
    ['A bug introduced during the build', 'The build log file', 'A packaged output of the build (binary, image, bundle) that can be deployed or tested', 'A temporary cache folder'], 'C',
    'Artifacts are the products of a build — a JAR, a Docker image, a frontend bundle — stored and promoted through environments.', ['ci', 'artifacts']),
  m(CI, 'easy', 'In a typical pipeline, which check should run first?',
    ['End-to-end tests', 'Manual exploratory testing', 'Performance tests', 'Linting and unit tests'], 'D',
    'Fast, cheap checks run first to fail fast. Slow and expensive suites (E2E, performance) run later, often after deployment to a test environment.', ['pipeline', 'fail-fast']),

  // ── multiple / medium ──
  m(CI, 'medium', 'What is the difference between Continuous Delivery and Continuous Deployment?',
    ['Delivery deploys automatically to production; Deployment requires approval', 'Delivery keeps every build deployable with a manual release decision; Deployment releases every passing build automatically', 'Delivery is for backend, Deployment for frontend', 'There is no difference'], 'B',
    'The difference is the final gate: Continuous Delivery has a human decision to release; Continuous Deployment is fully automatic to production.', ['cd']),
  m(CI, 'medium', 'Why are flaky tests especially harmful in CI?',
    ['They erode trust in the pipeline, causing teams to ignore or rerun real failures', 'They consume more memory', 'They only fail on Fridays', 'They cannot be deleted'], 'A',
    'Once a team starts rerunning red builds out of habit, genuine regressions slip through. Flaky tests must be quarantined and fixed quickly.', ['flaky-tests']),
  m(CI, 'medium', 'What is the purpose of caching dependencies in a CI job?',
    ['To avoid running tests twice', 'To keep secrets out of logs', 'To speed up the pipeline by skipping repeated downloads', 'To pin dependency versions'], 'C',
    'Restoring node_modules, Maven or pip caches avoids re-downloading dependencies on every run, often saving several minutes per build.', ['ci', 'performance']),
  m(CI, 'medium', 'In pipeline terminology, what is the relationship between stages and steps?',
    ['A stage groups steps; steps are the individual commands or actions', 'A step groups stages', 'They are synonyms', 'Stages are manual, steps are automatic'], 'A',
    'Pipelines are organized into stages (build, test, deploy) and each stage contains ordered steps (checkout, install, run command).', ['pipeline']),
  m(CI, 'medium', 'When should smoke tests run in a deployment pipeline?',
    ['Before code review', 'Only in production', 'Instead of unit tests', 'Right after each deployment to an environment, to verify it is basically functional'], 'D',
    'Smoke tests are a quick post-deploy sanity check (app up, login works, key endpoints respond) before running deeper suites or routing traffic.', ['smoke-tests', 'pipeline']),
  m(CI, 'medium', 'What is test sharding/parallelization in CI for?',
    ['Running the same test multiple times to detect flakiness', 'Encrypting test results', 'Splitting the test suite across multiple runners to reduce total execution time', 'Skipping slow tests'], 'C',
    'Sharding distributes tests across parallel machines or containers; a 40-minute suite on 4 shards can finish in about 10 minutes.', ['ci', 'performance']),
  m(CI, 'medium', 'What is a matrix build in GitHub Actions?',
    ['Running the same job across combinations of parameters such as OS and language versions', 'A build that produces multiple artifacts', 'A visualization of the pipeline', 'A build triggered by multiple events'], 'A',
    'The strategy.matrix keyword expands a job into one run per combination (e.g. node 18/20 × ubuntu/windows), all in parallel.', ['github-actions']),
  m(CI, 'medium', 'How should secrets (API keys, passwords) be handled in CI?',
    ['Committed to the repo in an encrypted file', 'Hardcoded in the pipeline YAML', 'Stored in the CI platform secret store and injected as masked environment variables', 'Sent by email to the build agent'], 'C',
    'CI platforms provide encrypted secret stores; values are injected at runtime and masked in logs. Secrets must never live in the repository.', ['security', 'secrets']),
  m(CI, 'medium', 'What is a quality gate?',
    ['A firewall rule for the build server', 'A set of criteria (tests passing, coverage, no critical issues) that must be met before code can progress', 'The final manual approval by a manager', 'A code freeze period'], 'B',
    'Quality gates automate the go/no-go decision: e.g. all tests green, coverage above threshold, zero critical static-analysis findings.', ['quality-gates']),
  m(CI, 'medium', 'What is the purpose of branch protection rules?',
    ['To prevent branches from being created', 'To encrypt branch contents', 'To automatically delete stale branches', 'To require checks like passing CI and reviews before merging to important branches'], 'D',
    'Branch protection enforces that PRs cannot merge to main without passing status checks, up-to-date branches and required approvals.', ['git', 'governance']),
  m(CI, 'medium', 'Why are Docker containers widely used in CI pipelines?',
    ['They provide a consistent, reproducible environment for every build', 'They make tests run without code', 'They are required by Git', 'They replace the need for artifacts'], 'A',
    'Containers pin the OS, runtime and dependencies, eliminating "works on my machine" differences between local and CI runs.', ['docker', 'ci']),
  m(CI, 'medium', 'What does "shift left" mean in the context of CI/CD?',
    ['Moving deployment to earlier in the week', 'Moving testing and quality activities earlier in the development cycle', 'Putting the test stage on the left of the dashboard', 'Migrating pipelines to another provider'], 'B',
    'Shift left means testing earlier: unit tests with the code, API tests on every PR, static analysis pre-merge — finding defects when they are cheapest to fix.', ['shift-left', 'strategy']),

  // ── multiple / hard ──
  m(CI, 'hard', 'What is a blue-green deployment?',
    ['Deploying twice a day', 'Two identical environments where traffic switches from the old (blue) to the new (green) at once, enabling instant rollback', 'Deploying backend and frontend separately', 'A deployment that requires database downtime'], 'B',
    'Blue-green keeps two production-grade environments. The new version deploys to the idle one, gets verified, then the router flips traffic. Rollback is flipping back.', ['deployment', 'blue-green']),
  m(CI, 'hard', 'What is a canary release?',
    ['Releasing only on weekends', 'Gradually routing a small percentage of real traffic to the new version while monitoring before full rollout', 'A release without tests', 'Deploying to a staging environment first'], 'B',
    'Canary releases expose the new version to e.g. 5% of users; if error rates and metrics stay healthy, traffic increases progressively until 100%.', ['deployment', 'canary']),
  m(CI, 'hard', 'What is test impact analysis?',
    ['Measuring how long each test takes', 'Counting how many bugs each test has found', 'Selecting and running only the tests affected by the code changes in a commit', 'Analyzing the business impact of skipped tests'], 'C',
    'Test impact analysis maps tests to the code they exercise so CI can run only the relevant subset per change, drastically cutting feedback time.', ['ci', 'optimization']),
  m(CI, 'hard', 'Which is the most sustainable strategy for dealing with a flaky test in CI?',
    ['Configure automatic retries forever', 'Delete it immediately', 'Mark it as expected to fail permanently', 'Quarantine it out of the blocking suite, fix the root cause, then restore it'], 'D',
    'Retries hide real races and rot trust. Quarantine keeps the pipeline trustworthy while the root cause (timing, test data, isolation) gets fixed with a deadline.', ['flaky-tests']),
  m(CI, 'hard', 'What advantage do feature flags give for releases and rollbacks?',
    ['Code can ship dark and a faulty feature can be disabled instantly without redeploying', 'They remove the need for version control', 'They speed up the build', 'They encrypt features in production'], 'A',
    'Flags decouple deploy from release: incomplete features ship disabled, and turning a flag off is an instant rollback with no pipeline run.', ['feature-flags', 'deployment']),
  m(CI, 'hard', 'According to the test pyramid, how should tests be distributed in a pipeline?',
    ['Mostly E2E tests, few unit tests', 'Equal numbers of each type', 'Many fast unit tests at the base, fewer integration tests, and a small set of E2E tests at the top', 'Only API tests'], 'C',
    'The pyramid maximizes fast, stable feedback: broad unit coverage runs on every commit, while slow, brittle E2E suites stay small and targeted.', ['test-pyramid', 'strategy']),
  m(CI, 'hard', 'What are ephemeral (preview) environments?',
    ['Environments that only exist during business hours', 'Production replicas with anonymized data', 'Environments that automatically self-destruct on failure', 'Short-lived environments spun up per pull request and destroyed after merge'], 'D',
    'Per-PR environments let QA and reviewers test each change in isolation with its own URL, then are torn down to save cost.', ['environments', 'pipeline']),
  m(CI, 'hard', 'What does "build once, deploy many" (artifact promotion) mean?',
    ['The exact same artifact that passed tests is promoted through dev, staging and production without rebuilding', 'Each environment rebuilds from the same commit', 'One build serves multiple applications', 'Builds are cached for one week'], 'A',
    'Rebuilding per environment risks differences between what was tested and what ships. Promoting the identical artifact guarantees you deploy what you verified.', ['artifacts', 'deployment']),

  // ── true/false ──
  tf(CI, 'easy', 'Continuous Integration encourages merging small changes frequently rather than large changes rarely.', true,
    'True. Small frequent merges keep integration conflicts tiny and feedback fast — the core idea of CI.', ['ci', 'basics']),
  tf(CI, 'easy', 'CI means every commit is automatically deployed to production.', false,
    'False. That describes Continuous Deployment. CI is about automatically building and testing each merged change.', ['ci', 'cd']),
  tf(CI, 'easy', 'Jenkins is a cloud-only service that cannot be self-hosted.', false,
    'False. Jenkins is open source and typically self-hosted; that is one of its defining characteristics versus SaaS CI providers.', ['jenkins']),
  tf(CI, 'medium', 'A Jenkinsfile should be version-controlled together with the application code.', true,
    'True. Pipeline-as-code lives in the repo, so pipeline changes are reviewed, versioned and reproducible like any other code.', ['jenkins', 'pipeline']),
  tf(CI, 'medium', 'Storing secrets in a committed .env file is acceptable as long as the repository is private.', false,
    'False. Private repos leak (forks, clones, breaches, logs). Secrets belong in the CI secret store or a vault, never in version control.', ['security', 'secrets']),
  tf(CI, 'medium', 'Running linting and unit tests before E2E tests makes the pipeline fail faster and waste fewer resources.', true,
    'True. Fail-fast ordering puts cheap checks first; there is no point running a 30-minute E2E suite on code that does not even lint.', ['pipeline', 'fail-fast']),
  tf(CI, 'medium', 'E2E tests should make up the majority of the tests executed in a pipeline.', false,
    'False. The test pyramid recommends the opposite: many unit tests, fewer integration tests, and a small set of E2E tests.', ['test-pyramid']),
  tf(CI, 'medium', 'GitHub Actions can run jobs on Linux, Windows and macOS runners.', true,
    'True. The runs-on key accepts ubuntu, windows and macos images, and matrix builds can target all three.', ['github-actions']),
  tf(CI, 'hard', 'In blue-green deployment, both environments serve production traffic simultaneously at 50/50.', false,
    'False. Only one environment serves traffic at a time; the switch is all-at-once. Gradual traffic splitting describes a canary release.', ['blue-green', 'deployment']),
  tf(CI, 'hard', 'Artifact promotion means the same tested artifact moves through environments without being rebuilt.', true,
    'True. Build once, deploy many: rebuilding per environment would mean deploying something different from what was tested.', ['artifacts']),
  tf(CI, 'hard', 'A canary release deploys the new version to all users instantly.', false,
    'False. A canary release routes a small fraction of traffic first and expands gradually while monitoring. Instant full cutover is closer to blue-green.', ['canary', 'deployment']),
  tf(CI, 'hard', 'Feature flags allow disabling a faulty feature in production without a redeploy.', true,
    'True. Toggling the flag off removes the feature path immediately — the fastest rollback mechanism available.', ['feature-flags']),

  // ── open ──
  op(CI, 'easy', 'Explain the difference between Continuous Integration, Continuous Delivery and Continuous Deployment.',
    'CI: merge small changes frequently; every merge triggers automated build and tests. Continuous Delivery: on top of CI, every passing build is packaged and ready to release; deploying to production is a manual decision (one click). Continuous Deployment: removes that manual gate — every change that passes the pipeline goes to production automatically.', ['ci', 'cd', 'basics']),
  op(CI, 'medium', 'Describe the stages you would include in a CI pipeline for a web application with automated tests.',
    'Typical flow: 1) checkout + dependency install (cached); 2) static checks — lint, type-check, security scan; 3) unit tests with coverage gate; 4) build artifact / Docker image; 5) integration and API tests; 6) deploy to ephemeral or staging environment; 7) smoke tests, then E2E suite; 8) optional performance/accessibility checks; 9) publish artifact and report results. Fast stages first, each stage gating the next.', ['pipeline', 'design']),
  op(CI, 'medium', 'How do you deal with flaky tests in CI?',
    'Detect: track pass/fail history to identify tests that flip without code changes. Contain: quarantine them out of the blocking suite so trust in red builds survives. Fix root causes: hard waits → proper synchronization, shared test data → isolation, order dependence → independent setup, race conditions in the app itself. Set a quarantine deadline so they get fixed or deleted, and monitor a flakiness dashboard.', ['flaky-tests']),
  op(CI, 'medium', 'What is the role of QA in a team practicing CI/CD?',
    'QA shifts from gatekeeper to quality enabler: designing the automation strategy (what runs at which stage), writing and maintaining API/E2E suites in the pipeline, defining quality gates, doing exploratory testing on preview environments, monitoring production signals (errors, canary metrics), and coaching developers on testability. Manual regression cycles shrink; risk analysis and automation architecture grow.', ['qa-role', 'strategy']),
  op(CI, 'hard', 'Your test suite takes 60 minutes in CI. How would you reduce it?',
    'Measure first: find the slowest tests and stages. Then: parallelize/shard across runners; cache dependencies and Docker layers; move UI tests down the pyramid to API/unit level where possible; remove redundant and obsolete tests; run only impacted tests per PR (test impact analysis) with the full suite nightly; replace hard sleeps with proper waits; use faster test data setup (API/DB seeding instead of UI). Target: PR feedback under 10-15 minutes.', ['optimization', 'performance']),
  op(CI, 'hard', 'Would you run the full E2E suite on every pull request? Justify your strategy.',
    'Usually no. On every PR: lint, unit, API tests and a small E2E smoke subset (critical paths) for feedback in minutes. Full E2E runs on merge to main and nightly, plus on-demand for risky changes. This balances fast developer feedback against coverage; the key is choosing the smoke subset by risk and keeping the full suite green so nightly failures are meaningful.', ['strategy', 'e2e']),
  op(CI, 'hard', 'How would you implement quality gates in a pipeline? Which metrics would you use?',
    'Gates per stage: merge gate — build passes, lint/type-check clean, unit tests green, coverage at or above an agreed threshold on changed code, no new critical static-analysis or dependency vulnerabilities. Deploy gate — API/integration suites green, smoke tests pass post-deploy. Release gate — E2E green, error rate and latency within SLO during canary. Make thresholds visible and agreed by the team; gates should block automatically, not depend on someone remembering to check.', ['quality-gates', 'metrics']),
]

// ═══════════════════════════════════════════════════════════════════════
// SQL FOR QA — 28 multiple, 11 true/false, 7 open (46)
// ═══════════════════════════════════════════════════════════════════════

const SQL_QUESTIONS: ExtraQuestionSeed[] = [
  // ── multiple / easy ──
  m(SQL, 'easy', 'Which clause filters rows in a SELECT statement?',
    ['ORDER BY', 'WHERE', 'GROUP BY', 'SELECT'], 'B',
    'WHERE filters rows before grouping. ORDER BY sorts, GROUP BY aggregates.', ['select', 'basics']),
  m(SQL, 'easy', 'Which keyword removes duplicate rows from a result set?',
    ['UNIQUE', 'DEDUPE', 'DISTINCT', 'SINGLE'], 'C',
    'SELECT DISTINCT returns only unique rows for the selected columns.', ['select', 'basics']),
  m(SQL, 'easy', 'What is the default sort direction of ORDER BY?',
    ['Ascending (ASC)', 'Descending (DESC)', 'Random', 'Insertion order'], 'A',
    'ORDER BY sorts ascending unless DESC is specified.', ['order-by', 'basics']),
  m(SQL, 'easy', 'Which statement adds new rows to a table?',
    ['UPDATE', 'ALTER', 'CREATE', 'INSERT'], 'D',
    'INSERT INTO table (cols) VALUES (...) adds rows. UPDATE modifies existing rows; ALTER changes the table structure.', ['insert', 'basics']),
  m(SQL, 'easy', 'What does COUNT(*) return?',
    ['The number of columns in the table', 'The total number of rows matching the query', 'Only rows with no NULL values', 'The size of the table in bytes'], 'B',
    'COUNT(*) counts all matching rows, including those containing NULLs.', ['aggregates']),
  m(SQL, 'easy', 'Which operator is used for pattern matching in a WHERE clause?',
    ['LIKE', 'MATCH', 'REGEX', 'SIMILAR'], 'A',
    "LIKE matches patterns with wildcards: % (any sequence) and _ (single character), e.g. WHERE email LIKE '%@gmail.com'.", ['where', 'like']),
  m(SQL, 'easy', 'What is the correct way to check for NULL values?',
    ['WHERE column = NULL', 'WHERE column == NULL', 'WHERE column IS NULL', 'WHERE column EQUALS NULL'], 'C',
    'NULL is not a value and cannot be compared with =. Use IS NULL / IS NOT NULL.', ['null', 'where']),
  m(SQL, 'easy', 'Why is SQL a valuable skill for a QA engineer?',
    ['To replace developers', 'To design database schemas', 'To administer database servers', 'To verify directly in the database that the application stored and modified data correctly'], 'D',
    'QA uses SQL to validate persistence behind the UI/API, prepare test data, and investigate defects beyond what the interface shows.', ['qa', 'basics']),

  // ── multiple / medium ──
  m(SQL, 'medium', 'What does a FULL OUTER JOIN return?',
    ['All rows from both tables, matched where possible and NULL-filled where there is no match', 'Only the rows that match in both tables', 'The cartesian product of both tables', 'Only rows that do not match'], 'A',
    'FULL OUTER JOIN combines LEFT and RIGHT JOIN behavior: every row from both sides appears, useful for two-way reconciliation between tables.', ['joins']),
  m(SQL, 'medium', 'Why is HAVING needed when WHERE already exists?',
    ['HAVING is just an alias of WHERE', 'HAVING runs faster', 'HAVING filters on aggregate results (e.g. COUNT, SUM) after GROUP BY; WHERE cannot', 'WHERE only works on text columns'], 'C',
    'WHERE filters rows before grouping; HAVING filters groups after aggregation, e.g. HAVING COUNT(*) > 1.', ['group-by', 'having']),
  m(SQL, 'medium', 'What is the difference between UNION and UNION ALL?',
    ['UNION ALL removes duplicates; UNION keeps them', 'UNION removes duplicate rows; UNION ALL keeps every row and is faster', 'UNION ALL also joins tables horizontally', 'No difference'], 'B',
    'UNION deduplicates the combined result (extra sort cost). UNION ALL simply concatenates, which is faster and often what you want for counts.', ['union']),
  m(SQL, 'medium', 'Which query finds duplicate emails in a users table?',
    ['SELECT email FROM users WHERE COUNT(email) > 1', 'SELECT DISTINCT email FROM users', 'SELECT email FROM users GROUP BY email HAVING COUNT(*) > 1', 'SELECT email FROM users ORDER BY email'], 'C',
    'Group by the column and keep groups with more than one row. Aggregates in conditions require HAVING, not WHERE.', ['group-by', 'duplicates']),
  m(SQL, 'medium', 'What is the difference between DELETE and TRUNCATE?',
    ['DELETE removes rows (optionally filtered, logged, can be rolled back in a transaction); TRUNCATE quickly empties the whole table', 'TRUNCATE can use a WHERE clause', 'DELETE also drops the table structure', 'They are identical'], 'A',
    'DELETE is row-by-row DML supporting WHERE and triggers. TRUNCATE deallocates all data at once, cannot filter, and typically resets identity counters.', ['delete', 'truncate']),
  m(SQL, 'medium', 'What is a primary key?',
    ['The first column of a table', 'A column or set of columns that uniquely identifies each row and cannot be NULL', 'An encrypted column', 'The fastest column to query'], 'B',
    'A primary key enforces uniqueness and NOT NULL, and is the standard target for foreign key references.', ['constraints', 'keys']),
  m(SQL, 'medium', 'What does a foreign key enforce?',
    ['That a column is always indexed', 'That values are unique within the table', 'That the column cannot store numbers', 'Referential integrity: the value must exist in the referenced table'], 'D',
    'A foreign key guarantees that, e.g., orders.user_id always points to an existing users.id, preventing orphan records.', ['constraints', 'keys']),
  m(SQL, 'medium', 'Which query returns users who have placed at least one order, using a subquery?',
    ['SELECT * FROM users WHERE id IN (SELECT user_id FROM orders)', 'SELECT * FROM users WHERE id = (SELECT * FROM orders)', 'SELECT * FROM users JOIN orders', 'SELECT * FROM orders WHERE user_id IN users'], 'A',
    'IN with a subquery checks membership against the set of user_ids present in orders. A JOIN with DISTINCT is an equivalent alternative.', ['subqueries']),
  m(SQL, 'medium', 'Is BETWEEN inclusive of its boundary values?',
    ['No, it excludes both boundaries', 'Only the lower boundary is included', 'Yes — BETWEEN 1 AND 10 includes both 1 and 10', 'It depends on the column type only'], 'C',
    'BETWEEN is inclusive on both ends. Watch out with timestamps: BETWEEN \'2026-01-01\' AND \'2026-01-31\' misses times after midnight on the 31st.', ['where', 'between']),
  m(SQL, 'medium', 'What is the purpose of LIMIT (or TOP in SQL Server)?',
    ['To limit which columns are returned', 'To restrict user permissions', 'To cap query execution time', 'To return only the first N rows of the result'], 'D',
    'LIMIT N truncates the result set, commonly combined with ORDER BY for top-N queries and with OFFSET for pagination.', ['limit', 'pagination']),
  m(SQL, 'medium', 'Which of the following is NOT an aggregate function?',
    ['SUM', 'AVG', 'COALESCE', 'MAX'], 'C',
    'COALESCE returns the first non-NULL argument per row — a scalar function. SUM, AVG and MAX aggregate over groups of rows.', ['aggregates', 'functions']),
  m(SQL, 'medium', 'What does COALESCE(phone, email, \'no contact\') return?',
    ['The first non-NULL value among the arguments', 'The concatenation of all three values', 'TRUE if any value is NULL', 'The last non-NULL value'], 'A',
    'COALESCE evaluates arguments left to right and returns the first that is not NULL — useful for fallbacks and report formatting.', ['null', 'functions']),

  // ── multiple / hard ──
  m(SQL, 'hard', 'Which window function pattern keeps only the most recent record per user?',
    ['GROUP BY user_id ORDER BY created_at', 'ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY created_at DESC) and filter rn = 1', 'SELECT DISTINCT user_id, created_at', 'MAX(created_at) without grouping'], 'B',
    'ROW_NUMBER partitioned per user and ordered by date descending numbers each user\'s rows; filtering rn = 1 in an outer query/CTE keeps the latest one.', ['window-functions']),
  m(SQL, 'hard', 'What is a correlated subquery?',
    ['A subquery executed once and cached', 'Two subqueries joined together', 'A subquery that references columns from the outer query, so it is evaluated per outer row', 'A subquery inside SELECT only'], 'C',
    'Because it depends on each outer row (e.g. WHERE o.user_id = u.id), it conceptually runs once per row — powerful but a frequent performance suspect.', ['subqueries', 'performance']),
  m(SQL, 'hard', 'In ACID, what does Isolation guarantee?',
    ['Concurrent transactions do not see each other\'s intermediate, uncommitted state', 'Data survives a server crash', 'Transactions either complete fully or not at all', 'Constraints are always valid'], 'A',
    'Isolation controls visibility between concurrent transactions (levels: read committed, repeatable read, serializable). Atomicity is all-or-nothing; Durability is crash survival.', ['transactions', 'acid']),
  m(SQL, 'hard', 'What is the main trade-off of adding an index to a table?',
    ['Faster writes but slower reads', 'Reads stay the same, writes get faster', 'It only consumes disk space with no other effect', 'Faster reads on that column, but slower INSERT/UPDATE/DELETE and extra storage'], 'D',
    'Every write must also maintain the index. Indexes pay off on frequently filtered/joined columns, not on write-heavy rarely-queried ones.', ['indexes', 'performance']),
  m(SQL, 'hard', 'What does this anti-join return? SELECT u.* FROM users u LEFT JOIN orders o ON o.user_id = u.id WHERE o.id IS NULL',
    ['Users that have at least one order', 'Users that have no orders', 'Orders without users', 'All users and all orders'], 'B',
    'The LEFT JOIN keeps all users; for users without orders the right side is NULL, and the WHERE keeps exactly those — a classic data-validation pattern for QA.', ['joins', 'anti-join']),
  m(SQL, 'hard', 'When would you use a self join?',
    ['To join a table with itself, e.g. employees to their managers stored in the same table', 'To duplicate a table', 'To speed up a slow join', 'To join tables from different databases'], 'A',
    'A self join uses two aliases of the same table to relate rows to other rows, e.g. e.manager_id = m.id, or to find pairs of duplicate records.', ['joins', 'self-join']),
  m(SQL, 'hard', 'Which statement about NOT IN versus NOT EXISTS is true?',
    ['They always return identical results', 'NOT IN is always faster', 'NOT EXISTS cannot use subqueries', 'If the subquery returns any NULL, NOT IN matches no rows, while NOT EXISTS behaves as expected'], 'D',
    'NOT IN with a NULL in the list yields UNKNOWN for every comparison, returning zero rows — a classic SQL trap. NOT EXISTS is NULL-safe.', ['null', 'subqueries']),
  m(SQL, 'hard', 'What is a CTE (WITH clause) and why use it?',
    ['A temporary permanent table', 'An index created at query time', 'A named subquery that makes complex queries readable and can be referenced multiple times, including recursively', 'A transaction checkpoint'], 'C',
    'WITH name AS (SELECT ...) defines a reusable building block, improving readability of multi-step logic and enabling recursive queries (e.g. org hierarchies).', ['cte']),

  // ── true/false ──
  tf(SQL, 'easy', 'WHERE can filter on the result of aggregate functions like SUM or COUNT.', false,
    'False. WHERE runs before aggregation. Filtering on aggregates requires HAVING after GROUP BY.', ['where', 'having']),
  tf(SQL, 'easy', 'DISTINCT removes duplicate rows from the result set.', true,
    'True. DISTINCT applies to the combination of all selected columns and keeps unique rows only.', ['select']),
  tf(SQL, 'easy', 'The expression column = NULL is the correct way to find NULL values.', false,
    'False. Comparing anything with NULL yields UNKNOWN, so no rows match. Use IS NULL.', ['null']),
  tf(SQL, 'medium', 'A LEFT JOIN returns all rows from the left table even when there is no match in the right table.', true,
    'True. Unmatched left rows appear with NULLs in the right-side columns — the basis of anti-join validation queries.', ['joins']),
  tf(SQL, 'medium', 'TRUNCATE deletes rows one by one and fires row-level delete triggers.', false,
    'False. That describes DELETE. TRUNCATE deallocates the data pages at once, does not fire row-level triggers, and accepts no WHERE.', ['truncate', 'delete']),
  tf(SQL, 'medium', 'UNION removes duplicate rows while UNION ALL keeps them.', true,
    'True. UNION performs deduplication (costly on large sets); UNION ALL concatenates everything as-is.', ['union']),
  tf(SQL, 'medium', 'HAVING is evaluated before WHERE in query execution.', false,
    'False. Logical order: FROM/JOIN → WHERE → GROUP BY → HAVING → SELECT → ORDER BY. WHERE filters rows first; HAVING filters groups later.', ['execution-order']),
  tf(SQL, 'medium', 'An INNER JOIN excludes rows that have no match in the joined table.', true,
    'True. Only rows with matches on both sides survive an INNER JOIN.', ['joins']),
  tf(SQL, 'hard', 'Adding an index always improves overall database performance.', false,
    'False. Indexes speed up specific reads but slow down every write and consume storage. Useless indexes are pure overhead.', ['indexes', 'performance']),
  tf(SQL, 'hard', 'ROLLBACK undoes the changes made since the transaction began.', true,
    'True. Inside a transaction, ROLLBACK reverts all uncommitted changes; COMMIT makes them permanent. Useful for QA to test without dirtying data.', ['transactions']),
  tf(SQL, 'hard', 'COUNT(column) includes rows where that column is NULL.', false,
    'False. COUNT(column) counts only non-NULL values; COUNT(*) counts all rows. The difference between them is a handy NULL-count check.', ['aggregates', 'null']),

  // ── open ──
  op(SQL, 'easy', 'Why does a QA engineer need SQL? Give concrete situations.',
    'Verifying that UI/API actions persisted correctly (the response can lie; the database does not). Preparing and cleaning test data faster than through the UI. Investigating bugs: checking whether bad data comes from the app or was already stored. Validating reports and calculations against source data. Backend testing where no UI exists (batch jobs, migrations).', ['qa', 'basics']),
  op(SQL, 'medium', 'You created a user through the UI. How do you verify with SQL that it was saved correctly?',
    "Query the table directly: SELECT * FROM users WHERE email = 'test@example.com'. Verify: the row exists (exactly one), every field matches the input, defaults and timestamps are set (created_at, status), the password is hashed and not plain text, and related tables were populated if applicable (profile, audit log). Also test the negative: a failed validation in the UI must NOT insert a row.", ['verification', 'test-design']),
  op(SQL, 'medium', 'Write a query to find duplicate emails in a users table and explain it.',
    'SELECT email, COUNT(*) AS qty FROM users GROUP BY email HAVING COUNT(*) > 1; — GROUP BY collapses rows per email, COUNT(*) measures each group size and HAVING keeps groups with more than one row. To see the full duplicate rows, join this result back to users or use ROW_NUMBER() OVER (PARTITION BY email) and filter rn > 1.', ['duplicates', 'group-by']),
  op(SQL, 'medium', 'How do you use SQL for test data setup and cleanup in automated tests?',
    'Setup: INSERT seed rows (or call data-builder scripts) before tests so each test owns its data; use unique identifiers (e.g. prefixed emails) to avoid collisions. Cleanup: DELETE the created rows in teardown, or run each test inside a transaction and ROLLBACK. Rules: never depend on data created by another test, keep scripts idempotent, and never point them at production.', ['test-data', 'automation']),
  op(SQL, 'hard', 'How would you validate a data migration between an old and a new table or database using SQL?',
    'Counts first: total rows per table and per status/date segment must match. Aggregate checksums: SUM/MIN/MAX on key numeric columns, counts of NULLs per column. Row-level diff on a sample or full set: join old and new on the business key and compare columns (or EXCEPT/MINUS queries both directions). Verify orphans with anti-joins, constraint validity in the target, and spot-check transformed fields against mapping rules. Automate it so it can re-run after each migration attempt.', ['migration', 'verification']),
  op(SQL, 'hard', 'How would you test database constraints (NOT NULL, UNIQUE, foreign keys) from a QA perspective?',
    'Try to violate each one and assert the database rejects it: INSERT with NULL in NOT NULL columns, duplicate values in UNIQUE columns, foreign keys pointing to nonexistent ids, and DELETE of a parent row with children (check expected behavior: restrict vs cascade). Verify the application layer surfaces these errors gracefully instead of a 500. Also confirm constraints actually exist in the schema (information_schema) — missing constraints are a common defect in new tables.', ['constraints', 'test-design']),
  op(SQL, 'hard', 'Explain how you would obtain the latest record per user from an events table, and why GROUP BY alone is not enough.',
    'GROUP BY user_id with MAX(created_at) gives the latest timestamp but cannot safely return the other columns of that row. Solutions: ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY created_at DESC) in a CTE and filter rn = 1 (cleanest, handles ties deterministically with a tiebreaker column); or join the table back to the MAX(created_at) per user (can return duplicates on exact ties). This pattern is essential for validating "current state" business logic.', ['window-functions', 'cte']),
]

// ═══════════════════════════════════════════════════════════════════════

export const VOLUME_QUESTIONS: ExtraQuestionSeed[] = [
  ...API_QUESTIONS,
  ...CI_QUESTIONS,
  ...SQL_QUESTIONS,
]
